import type { CoordinateMap } from '../../types';

export const TDS: CoordinateMap = [
  {
    pageNumber: 1,
    fields: {
      'header.property_address': { x: 0, y: 0, w: 0, fontSize: 9 },
      'header.city': { x: 0, y: 0, w: 0, fontSize: 9 },
      'header.county': { x: 0, y: 0, w: 0, fontSize: 9 },
      'header.described': { x: 0, y: 0, w: 0, fontSize: 9 },
      'header.as_of_date': { x: 0, y: 0, w: 0, fontSize: 9 },
      'coordination.described': { x: 0, y: 0, w: 0, fontSize: 9 },
      'coordination.inspection_reports': { x: 0, y: 0, w: 0, fontSize: 9 },
      'coordination.additional_inspection_reports': { x: 0, y: 0, w: 0, fontSize: 9 },
      'coordination.no_substitute_disclosure': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.seller_occupied': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.seller_not_occupied': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.range': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.wall_window_air_cond': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.pool': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.oven': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.sprinklers': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.pool_child_resistant_barrier': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.microwave': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.public_sewer_system': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.pool_spa_heater': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.dishwasher': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.septic_tank': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.pool_spa_heater_gas': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.pool_spa_heater_solar': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.pool_spa_heater_electric:': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.trash_compactor': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.sump_pump:': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.water_heater': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.garbage_disposal': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.water_softener': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.water_heater_gas:': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.water_heater_solar:': { x: 0, y: 0, w: 0, fontSize: 9 },
      'seller_info.a.water_heater_electric': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.washer_dryer_hookups:': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.patio_decking': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.water_supply': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.rain_gutters': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.built_in_barbecue': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.water_supply_city': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.water_supply_well': { x: 0, y: 0, w: 0, fontSize: 9 },  
      'seller_info.a.burglar_alarms': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.gazebo': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.water_supply_private_utility': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.water_supply_other': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.smoke_detector': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.garage': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.gas_supply': { x: 0, y: 0, w: 0, fontSize: 9 }, 

      'seller_info.a.fire_alarms': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.garage_attached': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.garage_not_attached': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.gas_supply_utility': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.gas_supply_bottled_tank': { x: 0, y: 0, w: 0, fontSize: 9 }, 

      'seller_info.a.tv_antenna': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.garage_carport': { x: 0, y: 0, w: 0, fontSize: 9 }, 
      'seller_info.a.gas_supply_window_screens': { x: 0, y: 0, w: 0, fontSize: 9 }, 
    },
  },
  {
    pageNumber: 2,
    fields: {},
  },
  {
    pageNumber: 3,
    fields: {},
  },
];
