/**
 * Blocker / Warning catalog for the CONTRACT stage.
 *
 * CONVENTIONS
 * ────────────
 * 1. Add a new entry here every time you write a new rule in contract.stage.ts.
 * 2. Use the `code` field as the RuleIssue.code emitted by rule functions.
 * 3. Set `effective: false` to retire a rule — never delete an entry.
 * 4. Number ranges (see validator.types.ts for full table):
 *    RPA-specific:   1–1000
 *    RPA-cross-form: 1001–2000
 *    RPA-business:   2001–3000
 *    AD-specific:    5001–6000
 *    AVID-specific:  25001–26000
 *    BIA-specific:   30001–31000
 *
 * 5. `combinations` format: FORMCODE:versionList.
 *    Use '*' for all versions, e.g. ['RPA:*', 'AD:v1,v4,v5'].
 *    Currently documentation-only; rule functions handle preconditions.
 */

import type { BlockerWarningEntry } from '../validator.types';

/**
 * Single source of truth for the required C.A.R. form revision per form
 * code. Update the value here to change what a form's revision blocker
 * requires — no validator logic needs to change. A form code absent from
 * this map has no revision requirement and its revision blocker never fires.
 */
export const REQUIRED_FORM_REVISIONS: Record<string, string> = {
  RPA: '6/26',
  SCO: '6/26',
  BCO: '6/26',
  SMCO: '6/26',
};

export const CONTRACT_BLOCKER_CATALOG: Record<string, BlockerWarningEntry> = {

  // ── RPA form-specific (1–1000) ────────────────────────────────────────────

  BLOCKER_BUYER_MISSING: {
    id: 'BLOCKER_BUYER_MISSING',
    compositeId: 'BLOCKER-RPA-1',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'No buyer identified on the purchase agreement (Section 1A, Page 1)',
    description: 'The RPA must name at least one buyer to form a valid contract',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_SELLER_MISSING: {
    id: 'BLOCKER_SELLER_MISSING',
    compositeId: 'BLOCKER-RPA-2',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'No seller identified on the purchase agreement (Section 1A, Page 1)',
    description: 'The RPA must name at least one seller to form a valid contract',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_PURCHASE_PRICE: {
    id: 'BLOCKER_PURCHASE_PRICE',
    compositeId: 'BLOCKER-RPA-3',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Purchase price is missing or zero (Section 3A, Page 1)',
    description: 'A valid positive purchase price is required for the contract',
    category: 'financial',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_PROPERTY_STREET: {
    id: 'BLOCKER_PROPERTY_STREET',
    compositeId: 'BLOCKER-RPA-4',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Property street address not found (Section 1B, Page 1)',
    description: 'The property street address is required on the RPA',
    category: 'property',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_PROPERTY_CITY: {
    id: 'BLOCKER_PROPERTY_CITY',
    compositeId: 'BLOCKER-RPA-5',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Property city not found (Section 1B, Page 1)',
    description: 'The property city is required on the RPA',
    category: 'property',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_PROPERTY_STATE: {
    id: 'BLOCKER_PROPERTY_STATE',
    compositeId: 'BLOCKER-RPA-6',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Property state not found (Section 1B, Page 1)',
    description: 'The property state is required on the RPA',
    category: 'property',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_OFFER_DATE: {
    id: 'BLOCKER_OFFER_DATE',
    compositeId: 'BLOCKER-RPA-7',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Offer date not found or invalid (RPA header, Page 1)',
    description: 'The offer date must be present and parseable',
    category: 'dates',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_CLOSING_DATE: {
    id: 'BLOCKER_CLOSING_DATE',
    compositeId: 'BLOCKER-RPA-8',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Close of escrow date not found or invalid (Section 3B, Page 1)',
    description: 'The closing date must be present and valid',
    category: 'dates',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_BUYER_SIGNATURE: {
    id: 'BLOCKER_BUYER_SIGNATURE',
    compositeId: 'BLOCKER-RPA-9',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Buyer signature not detected (Section 32, Offer Expiration and Acceptance, Page 16)',
    description: 'At least one buyer must sign the offer for the RPA to be valid',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_BUYER_NAME: {
    id: 'WARN_BUYER_NAME',
    compositeId: 'WARN-RPA-10',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'One or more buyers are missing a full name (Section 1A, Page 1)',
    description: 'All buyers should have a complete name on the RPA',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SELLER_NAME: {
    id: 'WARN_SELLER_NAME',
    compositeId: 'WARN-RPA-11',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'One or more sellers are missing a full name (Section 1A, Page 1)',
    description: 'All sellers should have a complete name on the RPA',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_PROPERTY_ZIP: {
    id: 'WARN_PROPERTY_ZIP',
    compositeId: 'WARN-RPA-12',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Property postal code not found (Section 1B, Page 1)',
    description: 'Postal code is recommended but not required for contract formation',
    category: 'property',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_PROPERTY_APN: {
    id: 'WARN_PROPERTY_APN',
    compositeId: 'WARN-RPA-13',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'APN not found — verify it appears on title (Section 1B, Page 1)',
    description: 'The Assessor Parcel Number should be on the RPA for title verification',
    category: 'property',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_EARNEST_MONEY: {
    id: 'WARN_EARNEST_MONEY',
    compositeId: 'WARN-RPA-14',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Initial deposit / earnest money amount not found (Section 3D1, Page 1)',
    description: 'Earnest money deposit amount is expected on the RPA',
    category: 'financial',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_FINANCING_TYPE: {
    id: 'WARN_FINANCING_TYPE',
    compositeId: 'WARN-RPA-15',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Financing type not specified (Section 3E1, Page 1)',
    description: 'Cash / Conventional / FHA / VA should be indicated on the RPA',
    category: 'financial',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_ACCEPTANCE_DATE: {
    id: 'WARN_ACCEPTANCE_DATE',
    compositeId: 'WARN-RPA-16',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Acceptance date not found — may be pending counter-offer (Seller Acceptance block, Page 16)',
    description: 'The seller acceptance date is expected once the contract is ratified',
    category: 'dates',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SELLER_SIGNATURE: {
    id: 'WARN_SELLER_SIGNATURE',
    compositeId: 'WARN-RPA-17',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Seller signature not detected — may be a pending counter-offer (Seller Acceptance block, Page 16)',
    description: 'Seller signature is expected once the contract is ratified',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_SELLER_SIGNATURE: {
    id: 'BLOCKER_SELLER_SIGNATURE',
    compositeId: 'BLOCKER-RPA-10',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Seller signature missing — the contract is not fully executed (Seller Acceptance block, Section 33, Page 16)',
    description: 'At least one seller must sign the Seller Acceptance section before the contract can proceed',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-24',
  },

  BLOCKER_BUYER_SIGNATURE_DATE: {
    id: 'BLOCKER_BUYER_SIGNATURE_DATE',
    compositeId: 'BLOCKER-RPA-11',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Buyer signature date missing — the contract is not fully executed (Buyer Acceptance, Section 32, Page 16)',
    description: 'Buyer signature is present but the date next to it is missing',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-24',
  },

  BLOCKER_SELLER_SIGNATURE_DATE: {
    id: 'BLOCKER_SELLER_SIGNATURE_DATE',
    compositeId: 'BLOCKER-RPA-12',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Seller signature date missing — the contract is not fully executed (Seller Acceptance, Section 33, Page 16)',
    description: 'Seller signature is present but the date next to it is missing',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-24',
  },

  BLOCKER_INITIAL_BUYER_LD: {
    id: 'BLOCKER_INITIAL_BUYER_LD',
    compositeId: 'BLOCKER-RPA-13',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Buyer must initial Liquidated Damages clause (Paragraph 29), RPA Page 15',
    description: 'Buyer handwritten initials are required on the Liquidated Damages provision',
    category: 'initials',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-24',
  },

  BLOCKER_INITIAL_SELLER_LD: {
    id: 'BLOCKER_INITIAL_SELLER_LD',
    compositeId: 'BLOCKER-RPA-14',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Seller must initial Liquidated Damages clause (Paragraph 29), RPA Page 15',
    description: 'Seller handwritten initials are required on the Liquidated Damages provision',
    category: 'initials',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-24',
  },

  BLOCKER_INITIAL_BUYER_AR: {
    id: 'BLOCKER_INITIAL_BUYER_AR',
    compositeId: 'BLOCKER-RPA-15',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Buyer must initial Arbitration clause (Paragraph 31), RPA Page 15',
    description: 'Buyer handwritten initials are required on the Arbitration provision',
    category: 'initials',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-24',
  },

  BLOCKER_INITIAL_SELLER_AR: {
    id: 'BLOCKER_INITIAL_SELLER_AR',
    compositeId: 'BLOCKER-RPA-16',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Seller must initial Arbitration clause (Paragraph 31), RPA Page 15',
    description: 'Seller handwritten initials are required on the Arbitration provision',
    category: 'initials',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-24',
  },

  BLOCKER_RPA_INVALID_REVISION: {
    id: 'BLOCKER_RPA_INVALID_REVISION',
    compositeId: 'BLOCKER-RPA-17',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: `The uploaded RPA is not the required Revised ${REQUIRED_FORM_REVISIONS.RPA} version. Upload the correct RPA form to continue.`,
    description: `The uploaded RPA form revision is not the required ${REQUIRED_FORM_REVISIONS.RPA} version (missing, unreadable, different, or conflicting between header and footer). Upload the correct RPA form to continue.`,
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-28',
  },

  BLOCKER_RPA_BUYER_INITIALS_MISSING: {
    id: 'BLOCKER_RPA_BUYER_INITIALS_MISSING',
    compositeId: 'BLOCKER-RPA-18',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Required Buyer initials are missing on an RPA page (see location and fields for details).',
    description: 'A Buyer must provide handwritten or electronic initials on the designated RPA page footer or section. Upload a corrected document or request the Buyer to initial the form.',
    category: 'initials',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-28',
  },

  BLOCKER_RPA_SELLER_INITIALS_MISSING: {
    id: 'BLOCKER_RPA_SELLER_INITIALS_MISSING',
    compositeId: 'BLOCKER-RPA-19',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Required Seller initials are missing on an RPA page (see location and fields for details).',
    description: 'A Seller must provide handwritten or electronic initials on the designated RPA page footer or section. Upload a corrected document or request the Seller to initial the form.',
    category: 'initials',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-28',
  },

  WARN_RPA_INITIALS_AMBIGUOUS: {
    id: 'WARN_RPA_INITIALS_AMBIGUOUS',
    compositeId: 'WARN-RPA-29',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Initials field mark is ambiguous and requires manual review.',
    description: 'A mark in an initials field overlaps another field or cannot be confidently assigned. Review the document and confirm whether the initials are valid.',
    category: 'initials',
    phase: 'contract',
    effective: false, // retired: initials classification is now strictly binary (present/missing) — no ambiguous/manual-review state
    introducedBy: 'system',
    dateAdded: '2026-07-28',
  },

  WARN_RPA_PARTY_COUNT_UNKNOWN: {
    id: 'WARN_RPA_PARTY_COUNT_UNKNOWN',
    compositeId: 'WARN-RPA-30',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'The number of Buyers or Sellers in the transaction could not be determined. Page-level initials validation was skipped.',
    description: 'The expected buyer or seller count is unavailable from extraction. Individual initials checks could not be run. Review the document manually for required initials.',
    category: 'initials',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-28',
  },

  WARN_RPA_MISSING_ESCROW_INFO: {
    id: 'WARN_RPA_MISSING_ESCROW_INFO',
    compositeId: 'WARN-RPA-31',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Escrow holder information is missing on RPA page 17 (Escrow Holder Acknowledgment).',
    description: 'Neither an escrow holder name nor an escrow number was found in the Escrow Holder Acknowledgment section on RPA page 17. This section is often completed by the escrow holder after acceptance, so this is a warning, not a blocker — confirm whether escrow has been opened and the acknowledgment page updated.',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-31',
  },

  WARN_RPA_PAGE17_ESCROW_SIGNATURE_MISSING: {
    id: 'WARN_RPA_PAGE17_ESCROW_SIGNATURE_MISSING',
    compositeId: 'WARN-RPA-32',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Escrow holder signature is missing on RPA page 17 (Escrow Holder Acknowledgment).',
    description: 'Escrow holder name/number is present, but the "By" signature line in the Escrow Holder Acknowledgment section on RPA page 17 is blank. This section is completed and signed by the escrow holder after acceptance, so this is a warning, not a blocker — the "Signed RPA" checklist item stays outstanding until it is signed.',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-09',
  },

  WARN_SIGNATURE_MISSING: {
    id: 'WARN_SIGNATURE_MISSING',
    compositeId: 'WARN-RPA-18',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Missing Signature in Seller Acceptance (Section 33, Page 16)',
    description: 'A required signature line in the Seller Acceptance section (Section 33, Page 16) is blank',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-13',
  },

  WARN_SIGNATURE_DATE_MISSING: {
    id: 'WARN_SIGNATURE_DATE_MISSING',
    compositeId: 'WARN-RPA-19',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Missing Signature Date in Seller Acceptance (Section 33, Page 16)',
    description: 'Signature is present in the Seller Acceptance section (Section 33, Page 16) but the date next to it is blank',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-13',
  },

  WARN_INSPECTION_CONTINGENCY: {
    id: 'WARN_INSPECTION_CONTINGENCY',
    compositeId: 'WARN-RPA-19',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Inspection contingency period not found — confirm if waived (Section 3L3, Page 2)',
    description: 'The physical inspection contingency days should be specified or explicitly waived',
    category: 'contingencies',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_LOAN_CONTINGENCY: {
    id: 'WARN_LOAN_CONTINGENCY',
    compositeId: 'WARN-RPA-20',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Loan contingency period not found — confirm if waived (Section 3L1, Page 2)',
    description: 'The loan contingency days should be specified or explicitly waived for financed purchases',
    category: 'contingencies',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_APPRAISAL_CONTINGENCY: {
    id: 'WARN_APPRAISAL_CONTINGENCY',
    compositeId: 'WARN-RPA-21',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Appraisal contingency period not found — confirm if waived (Section 3L2, Page 2)',
    description: 'The appraisal contingency days should be specified or explicitly waived',
    category: 'contingencies',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_DISCLOSURES_DUE: {
    id: 'WARN_DISCLOSURES_DUE',
    compositeId: 'WARN-RPA-22',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Disclosure deadline not found (Section 3N1, Page 2)',
    description: 'The number of days for disclosures should be stated on the RPA',
    category: 'contingencies',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_FORMS_FOUND: {
    id: 'WARN_FORMS_FOUND',
    compositeId: 'WARN-RPA-23',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'No forms or disclosures detected in the document (Section 4, Pages 4-16)',
    description: 'Expected attachments and addenda were not detected in extraction',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_MISSING_FORMS: {
    id: 'WARN_MISSING_FORMS',
    compositeId: 'WARN-RPA-24',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'One or more referenced forms are not attached (Section 4, Pages 4-16)',
    description: 'Forms referenced in the RPA checklist were not found in upload',
    category: 'forms_disclosures',
    phase: 'contract',
    // Retired: a referenced form not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker/warning.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_ESCROW_IDENTIFIED: {
    id: 'WARN_ESCROW_IDENTIFIED',
    compositeId: 'WARN-RPA-25',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'No escrow company found — may be specified in addendum (Section 3Q7, Page 3)',
    description: 'An escrow company should be named on the RPA or attached addendum',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── RPA cross-form (1001–2000) ────────────────────────────────────────────

  WARN_CROSS_BUYER_NAMES: {
    id: 'WARN_CROSS_BUYER_NAMES',
    compositeId: 'WARN-RPA-AD-1001',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*', 'AD:*'],
    message: 'Buyer names differ between RPA and Agency Disclosure',
    description: 'Buyer names should match across all forms in the contract package',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_CROSS_SELLER_NAMES: {
    id: 'WARN_CROSS_SELLER_NAMES',
    compositeId: 'WARN-RPA-AD-1002',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*', 'AD:*'],
    message: 'Seller names differ between RPA and Agency Disclosure',
    description: 'Seller names should match across all forms in the contract package',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_CROSS_BUYER_AGENT: {
    id: 'WARN_CROSS_BUYER_AGENT',
    compositeId: 'WARN-RPA-AD-1003',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*', 'AD:*'],
    message: 'Buyer agent name differs between RPA and Agency Disclosure',
    description: 'The buyer agent identified in the AD should match the RPA',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── RPA business rules (2001–3000) ────────────────────────────────────────

  BLOCKER_EARNEST_MONEY_RATIO: {
    id: 'BLOCKER_EARNEST_MONEY_RATIO',
    compositeId: 'BLOCKER-RPA-2001',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Earnest money exceeds purchase price (Section 3A / 3D1, Page 1)',
    description: 'The initial deposit amount must not be greater than the purchase price',
    category: 'financial',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_LOAN_AMOUNT: {
    id: 'BLOCKER_LOAN_AMOUNT',
    compositeId: 'BLOCKER-RPA-2002',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Loan amount missing for financed purchase (Section 3E1, Page 1)',
    description: 'A loan amount is required when the financing type is not cash',
    category: 'financial',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_LOAN_AMOUNT_RATIO: {
    id: 'BLOCKER_LOAN_AMOUNT_RATIO',
    compositeId: 'BLOCKER-RPA-2003',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Loan amount exceeds purchase price (Section 3A / 3E1, Page 1)',
    description: 'The loan amount must not exceed the purchase price',
    category: 'financial',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_ACCEPTANCE_BEFORE_OFFER: {
    id: 'BLOCKER_ACCEPTANCE_BEFORE_OFFER',
    compositeId: 'BLOCKER-RPA-2004',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Acceptance date is before offer date (Seller Acceptance / RPA header, Page 1 / 16)',
    description: 'The seller acceptance date must be on or after the offer date',
    category: 'dates',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_CLOSING_BEFORE_ACCEPTANCE: {
    id: 'BLOCKER_CLOSING_BEFORE_ACCEPTANCE',
    compositeId: 'BLOCKER-RPA-2005',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Closing date is not after acceptance/offer date (Section 3B / Seller Acceptance, Page 1 / 16)',
    description: 'The close of escrow date must be after the offer and acceptance dates',
    category: 'dates',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── AD form-specific (5001–6000) ──────────────────────────────────────────

  WARN_AD_AGENTS: {
    id: 'WARN_AD_AGENTS',
    compositeId: 'WARN-AD-5001',
    type: 'warning',
    formCode: 'AD',
    combinations: ['AD:*'],
    message: 'No buyer or seller agent identified in Agency Disclosure (Confirmation section, Page 1)',
    description: 'At least one real estate agent should be identified on the AD',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_BUYER_AGENT_PRESENT: {
    id: 'WARN_BUYER_AGENT_PRESENT',
    compositeId: 'WARN-AD-5002',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*'],
    message: 'No buyer agent found (Confirmation section, Page 1)',
    description: 'A buyer agent should be identified when one is acting in the transaction',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_LISTING_AGENT_PRESENT: {
    id: 'WARN_LISTING_AGENT_PRESENT',
    compositeId: 'WARN-AD-5003',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*'],
    message: 'No listing agent found (Confirmation section, Page 1)',
    description: 'A listing agent should be identified when one is acting in the transaction',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_BUYER_AGENT_LICENSE: {
    id: 'WARN_BUYER_AGENT_LICENSE',
    compositeId: 'WARN-AD-5004',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*'],
    message: 'Buyer agent(s) missing DRE license number (Confirmation section, Page 1)',
    description: 'The buyer agent DRE license number should appear on the AD',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_LISTING_AGENT_LICENSE: {
    id: 'WARN_LISTING_AGENT_LICENSE',
    compositeId: 'WARN-AD-5005',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*'],
    message: 'Listing agent(s) missing DRE license number (Confirmation section, Page 1)',
    description: 'The listing agent DRE license number should appear on the AD',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── AVID form-specific (25001–26000) ─────────────────────────────────────

  WARN_AVID_DEFECTS: {
    id: 'WARN_AVID_DEFECTS',
    compositeId: 'WARN-AVID-25001',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Agent noted visible defects — may require additional disclosure (Items Inspected, Page 1)',
    description: 'When visible defects are noted on the AVID, additional disclosure may be needed',
    category: 'property',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── BIA form-specific (30001–31000) ──────────────────────────────────────

  WARN_BIA_ACKNOWLEDGMENT: {
    id: 'WARN_BIA_ACKNOWLEDGMENT',
    compositeId: 'WARN-BIA-30001',
    type: 'warning',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer has not acknowledged the Buyer Inspection Advisory (Buyer Acknowledgement, Page 2)',
    description: 'The buyer must acknowledge the BIA by initialing or signing',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── Expected companion forms (progressive upload warnings) ────────────────

  WARN_MISSING_AD: {
    id: 'WARN_MISSING_AD',
    compositeId: 'WARN-RPA-26',
    type: 'warning',
    formCode: 'AD',
    combinations: ['RPA:*', 'AD:'],
    message: 'Agency Disclosure (AD) not yet uploaded',
    description: 'AD is expected alongside the RPA for the contract stage',
    category: 'forms_disclosures',
    phase: 'contract',
    // Retired: a companion form not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker/warning.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_MISSING_AVID: {
    id: 'WARN_MISSING_AVID',
    compositeId: 'WARN-RPA-27',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['RPA:*', 'AVID:'],
    message: 'Agent Visual Inspection Disclosure (AVID) not yet uploaded',
    description: 'AVID is expected alongside the RPA for the contract stage',
    category: 'forms_disclosures',
    phase: 'contract',
    // Retired: a companion form not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker/warning.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_MISSING_COUNTER_OFFER: {
    id: 'WARN_MISSING_COUNTER_OFFER',
    compositeId: 'WARN-RPA-2001',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Counter offer document expected but not uploaded',
    description: 'RPA indicates the seller acceptance is subject to a counter offer, but no counter offer form (SCO/BCO) was uploaded',
    category: 'forms_disclosures',
    phase: 'contract',
    // Retired: an expected companion document not yet uploaded is a checklist
    // concern (TransactionFormTemplatesService), never a validation blocker/warning.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_MISSING_BIA: {
    id: 'WARN_MISSING_BIA',
    compositeId: 'WARN-RPA-28',
    type: 'warning',
    formCode: 'BIA',
    combinations: ['RPA:*', 'BIA:'],
    message: 'Buyer Inspection Advisory (BIA) not yet uploaded',
    description: 'BIA is expected alongside the RPA for the contract stage',
    category: 'forms_disclosures',
    phase: 'contract',
    // Retired: a companion form not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker/warning.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── SCO per-form data quality warnings (35001–40000) ───────────────────

  BLOCKER_SCO_INVALID_REVISION: {
    id: 'BLOCKER_SCO_INVALID_REVISION',
    compositeId: 'BLOCKER-SCO-35008',
    type: 'blocker',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: `The uploaded Seller Counter Offer is not the required Revised ${REQUIRED_FORM_REVISIONS.SCO} version. Upload the correct SCO form to continue.`,
    description: `The uploaded SCO form revision is not the required ${REQUIRED_FORM_REVISIONS.SCO} version (missing, unreadable, or a different revision). Upload the correct SCO form to continue.`,
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-31',
  },

  BLOCKER_BCO_INVALID_REVISION: {
    id: 'BLOCKER_BCO_INVALID_REVISION',
    compositeId: 'BLOCKER-SCO-35009',
    type: 'blocker',
    formCode: 'BCO',
    combinations: ['BCO:*'],
    message: `The uploaded Buyer Counter Offer is not the required Revised ${REQUIRED_FORM_REVISIONS.BCO} version. Upload the correct BCO form to continue.`,
    description: `The uploaded BCO form revision is not the required ${REQUIRED_FORM_REVISIONS.BCO} version (missing, unreadable, or a different revision). Upload the correct BCO form to continue.`,
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-31',
  },

  BLOCKER_SMCO_INVALID_REVISION: {
    id: 'BLOCKER_SMCO_INVALID_REVISION',
    compositeId: 'BLOCKER-SCO-35010',
    type: 'blocker',
    formCode: 'SMCO',
    combinations: ['SMCO:*'],
    message: `The uploaded Seller Multiple Counter Offer is not the required Revised ${REQUIRED_FORM_REVISIONS.SMCO} version. Upload the correct SMCO form to continue.`,
    description: `The uploaded SMCO form revision is not the required ${REQUIRED_FORM_REVISIONS.SMCO} version (missing, unreadable, or a different revision). Upload the correct SMCO form to continue.`,
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-31',
  },

  WARN_SCO_PROPERTY_ADDRESS: {
    id: 'WARN_SCO_PROPERTY_ADDRESS',
    compositeId: 'WARN-SCO-35001',
    type: 'warning',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: 'Property address not found on counter offer (Header, Page 1)',
    description: 'The counter offer form must identify the property address',
    category: 'property',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SCO_BUYER_NAMES: {
    id: 'WARN_SCO_BUYER_NAMES',
    compositeId: 'WARN-SCO-35002',
    type: 'warning',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: 'Buyer names missing on counter offer (Parties, Page 1)',
    description: 'The counter offer must name the buyer(s)',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SCO_SELLER_NAMES: {
    id: 'WARN_SCO_SELLER_NAMES',
    compositeId: 'WARN-SCO-35003',
    type: 'warning',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: 'Seller names missing on counter offer (Parties, Page 1)',
    description: 'The counter offer must name the seller(s)',
    category: 'parties',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SCO_OFFER_REFERENCE: {
    id: 'WARN_SCO_OFFER_REFERENCE',
    compositeId: 'WARN-SCO-35004',
    type: 'warning',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: 'Referenced offer not identified on counter offer (Offer Reference, Page 1)',
    description: 'The counter offer must reference which offer it responds to',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SCO_OFFEROR_SIGNATURE: {
    id: 'WARN_SCO_OFFEROR_SIGNATURE',
    compositeId: 'WARN-SCO-35005',
    type: 'warning',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: 'Offeror signature missing on counter offer (Section 4, Page 1)',
    description: 'The offeror (seller on SCO, buyer on BCO) must sign Section 4',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SCO_ACCEPTOR_SIGNATURE: {
    id: 'WARN_SCO_ACCEPTOR_SIGNATURE',
    compositeId: 'WARN-SCO-35006',
    type: 'warning',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: 'Acceptor signature missing on counter offer (Section 5, Page 2)',
    description: 'The acceptor (buyer on SCO, seller on BCO) must sign Section 5',
    category: 'signatures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SCO_EXPIRATION: {
    id: 'WARN_SCO_EXPIRATION',
    compositeId: 'WARN-SCO-35007',
    type: 'warning',
    formCode: 'SCO',
    combinations: ['SCO:*'],
    message: 'Counter offer expiration date not found (Section 2, Page 1)',
    description: 'The counter offer must specify an expiration date and time',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ─── Contract chain warnings (RPA-business range 2002–2010) ───────────────

  WARN_CHAIN_FINAL_NOT_FOUND: {
    id: 'WARN_CHAIN_FINAL_NOT_FOUND',
    compositeId: 'WARN-RPA-2002',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Final accepted document not found.',
    description: 'No document in the contract negotiation chain is fully signed and accepted',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-13',
  },

  WARN_CHAIN_COUNTER_NOT_ACCEPTED: {
    id: 'WARN_CHAIN_COUNTER_NOT_ACCEPTED',
    compositeId: 'WARN-RPA-2004',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Counteroffer uploaded but not fully accepted.',
    description: 'A counter offer document exists in the chain but has not been signed by the required party',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-13',
  },

  WARN_CHAIN_LATER_SCO_NOT_ACCEPTED: {
    id: 'WARN_CHAIN_LATER_SCO_NOT_ACCEPTED',
    compositeId: 'WARN-RPA-2005',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Later Seller Counter Offer found but not fully accepted. Final contract document cannot be confirmed.',
    description: 'A later Seller Counter Offer exists in the chain but has not been accepted by the buyer',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-13',
  },

  WARN_CHAIN_MULTIPLE_SCO_AMBIGUOUS: {
    id: 'WARN_CHAIN_MULTIPLE_SCO_AMBIGUOUS',
    compositeId: 'WARN-RPA-2006',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Multiple counters found; latest accepted counter could not be determined.',
    description: 'Multiple counter offers exist but their sequence and acceptance status is unclear',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-13',
  },

  // ── Duplicate document blockers (RPA reserved 3001–4000) ──────────────────

  BLOCKER_DUPLICATE_TYPE_COUNTER: {
    id: 'BLOCKER_DUPLICATE_TYPE_COUNTER',
    compositeId: 'BLOCKER-RPA-3001',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*', 'SCO:*', 'BCO:*', 'SMCO:*', 'BMCO:*'],
    message: 'Duplicate document detected',
    description: 'Two documents represent the same contract in the negotiation chain (same form type and counter-offer number)',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-17',
  },

  BLOCKER_DUPLICATE_SAME_FILE: {
    id: 'BLOCKER_DUPLICATE_SAME_FILE',
    compositeId: 'BLOCKER-RPA-3002',
    type: 'blocker',
    formCode: 'RPA',
    combinations: ['RPA:*', 'SCO:*', 'BCO:*', 'SMCO:*', 'BMCO:*'],
    message: 'Duplicate contracts detected',
    description: 'Multiple documents share the same filename — verify they are distinct files',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-17',
  },

  WARN_DUPLICATE_SEMANTIC: {
    id: 'WARN_DUPLICATE_SEMANTIC',
    compositeId: 'WARN-RPA-3003',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*', 'SCO:*', 'BCO:*', 'SMCO:*', 'BMCO:*'],
    message: 'Possible duplicate document detected',
    description: 'Multiple documents share the same property address, acceptance date, and parties — verify they are distinct',
    category: 'forms_disclosures',
    phase: 'contract',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-17',
  },

  // ── Backup offer addendum warning (RPA reserved 2001–3000) ─────────────────

  WARN_MISSING_BACKUP_OFFER_ADDENDUM: {
    id: 'WARN_MISSING_BACKUP_OFFER_ADDENDUM',
    compositeId: 'WARN-RPA-2002',
    type: 'warning',
    formCode: 'RPA',
    combinations: ['RPA:*'],
    message: 'Back-Up Offer Addendum checked but not uploaded',
    description: 'RPA Section 33A indicates a Back-Up Offer Addendum should be attached, but no BUO form was found in the document package',
    category: 'forms_disclosures',
    phase: 'contract',
    // Retired: an expected companion document not yet uploaded is a checklist
    // concern (TransactionFormTemplatesService), never a validation blocker/warning.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-07-28',
  },
};

/** Resolve a contract-stage blocker code to its output shape. */
export function resolveContractBlocker(
  code: string,
  fields?: string[],
  location?: string,
): { code: string; compositeId: string; message: string; formCode: string; type: 'blocker'; fields?: string[]; location?: string } | null {
  const entry = CONTRACT_BLOCKER_CATALOG[code];
  if (!entry || !entry.effective || entry.type !== 'blocker') return null;
  return { code: entry.id, compositeId: entry.compositeId, message: entry.message, formCode: entry.formCode, type: 'blocker', fields, location };
}

/** Resolve a contract-stage warning code to its output shape. */
export function resolveContractWarning(
  code: string,
  fields?: string[],
  location?: string,
): { code: string; compositeId: string; message: string; formCode: string; type: 'warning'; fields?: string[]; location?: string } | null {
  const entry = CONTRACT_BLOCKER_CATALOG[code];
  if (!entry || !entry.effective || entry.type !== 'warning') return null;
  return { code: entry.id, compositeId: entry.compositeId, message: entry.message, formCode: entry.formCode, type: 'warning', fields, location };
}
