/**
 * Blocker / Warning catalog for the DISCLOSURES stage.
 *
 * CONVENTIONS
 * ────────────
 * 1. Add a new entry here every time you write a new rule in disclosures.stage.ts.
 * 2. Use the `code` field as the RuleIssue.code emitted by rule functions.
 * 3. Set `effective: false` to retire a rule — never delete an entry.
 * 4. Number ranges (see validator.types.ts for full table):
 *    TDS-specific: 10001–11000
 *    SPQ-specific: 15001–16000
 *    NHD-specific: 20001–21000
 *    AVID-specific: 25001–26000 (shared with contract stage)
 *
 * 5. `combinations` format: FORMCODE:versionList.
 *    Use '*' for all versions, e.g. ['TDS:*'].
 *    Currently documentation-only; rule functions handle preconditions.
 */

import type { BlockerWarningEntry } from '../validator.types';

export const DISCLOSURES_BLOCKER_CATALOG: Record<string, BlockerWarningEntry> = {

  // ── TDS form-specific (10001–11000) ───────────────────────────────────────

  BLOCKER_TDS_MISSING: {
    id: 'BLOCKER_TDS_MISSING',
    compositeId: 'BLOCKER-TDS-10001',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Transfer Disclosure Statement (TDS) is required but was not found',
    description: 'TDS is mandatory for the disclosures stage',
    category: 'forms_disclosures',
    phase: 'disclosure',
    // Retired: a required document not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_TDS_PROPERTY_ADDRESS: {
    id: 'WARN_TDS_PROPERTY_ADDRESS',
    compositeId: 'WARN-TDS-10003',
    type: 'warning',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Property address not identified on TDS (Header, Page 1)',
    description: 'The property address should be clearly indicated on the TDS form',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── TDS signature blockers (10007–10010) ──────────────────────────────────

  BLOCKER_TDS_SELLER_SIG: {
    id: 'BLOCKER_TDS_SELLER_SIG',
    compositeId: 'BLOCKER-TDS-10007',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Seller has not signed the TDS',
    description: 'The seller must sign the TDS (Page 2 or Page 3) to complete the disclosure',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_TDS_SELLER_DATE: {
    id: 'BLOCKER_TDS_SELLER_DATE',
    compositeId: 'BLOCKER-TDS-10008',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Seller signature date is missing on the TDS',
    description: 'The seller must date their signature on the TDS',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_TDS_BUYER_SIG: {
    id: 'BLOCKER_TDS_BUYER_SIG',
    compositeId: 'BLOCKER-TDS-10009',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Buyer has not signed the TDS',
    description: 'The buyer must acknowledge receipt by signing the TDS (Page 3)',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_TDS_BUYER_DATE: {
    id: 'BLOCKER_TDS_BUYER_DATE',
    compositeId: 'BLOCKER-TDS-10010',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Buyer signature date is missing on the TDS',
    description: 'The buyer must date their signature on the TDS',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_TDS_YES_ITEM_MISSING_EXPLANATION: {
    id: 'BLOCKER_TDS_YES_ITEM_MISSING_EXPLANATION',
    compositeId: 'BLOCKER-TDS-10011',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'TDS Section II.C item marked Yes has no corresponding explanation referencing its item number',
    description: 'Every "Yes" response in Section II.C must have an explanation that clearly identifies which item number it answers — a generic explanation with no item-number reference does not satisfy this for any specific item',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-14',
  },

  BLOCKER_TDS_YES_NO_NO_ANSWER_SELECTED: {
    id: 'BLOCKER_TDS_YES_NO_NO_ANSWER_SELECTED',
    compositeId: 'BLOCKER-TDS-10012',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'TDS Yes/No question has no answer selected',
    description: 'Every Yes/No question on the TDS must have exactly one of its two checkboxes marked — neither box is marked for this item',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-16',
  },

  BLOCKER_TDS_YES_NO_BOTH_SELECTED: {
    id: 'BLOCKER_TDS_YES_NO_BOTH_SELECTED',
    compositeId: 'BLOCKER-TDS-10013',
    type: 'blocker',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'TDS Yes/No question has both Yes and No marked',
    description: 'Every Yes/No question on the TDS must have exactly one of its two checkboxes marked — both boxes appear marked for this item',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-16',
  },

  // ── TDS warnings (retired — replaced by blockers above) ──────────────────

  WARN_TDS_SELLER_SIGNED: {
    id: 'WARN_TDS_SELLER_SIGNED',
    compositeId: 'WARN-TDS-10002',
    type: 'warning',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Seller has not signed the TDS (Signature page, Pages 2-3)',
    description: 'The seller must sign the TDS to complete the disclosure',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_TDS_SELLER_INFO_INCOMPLETE: {
    id: 'WARN_TDS_SELLER_INFO_INCOMPLETE',
    compositeId: 'WARN-TDS-10004',
    type: 'warning',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'TDS Section II (Seller\'s Information) appears incomplete (Pages 1-2)',
    description: 'Review property items, defects, and environmental disclosures for completeness',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_TDS_DEFECTS_NOT_DISCLOSED: {
    id: 'WARN_TDS_DEFECTS_NOT_DISCLOSED',
    compositeId: 'WARN-TDS-10005',
    type: 'warning',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'TDS Section II-B (Defects) marked as no defects without explanation context (Page 2)',
    description: 'Verify all structural components have been reviewed by the seller',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_TDS_BUYER_SIGNED: {
    id: 'WARN_TDS_BUYER_SIGNED',
    compositeId: 'WARN-TDS-10006',
    type: 'warning',
    formCode: 'TDS',
    combinations: ['TDS:*'],
    message: 'Buyer has not signed the TDS (Signature section, Page 3)',
    description: 'The buyer should acknowledge receipt by signing the TDS',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-06-20',
  },

  // ── SPQ signature blockers (15006–15009) ──────────────────────────────────

  BLOCKER_SPQ_SELLER_SIG: {
    id: 'BLOCKER_SPQ_SELLER_SIG',
    compositeId: 'BLOCKER-SPQ-15006',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Seller has not signed the SPQ',
    description: 'The seller must sign the SPQ (Signature section, Page 4)',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_SPQ_SELLER_DATE: {
    id: 'BLOCKER_SPQ_SELLER_DATE',
    compositeId: 'BLOCKER-SPQ-15007',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Seller signature date is missing on the SPQ',
    description: 'The seller must date their signature on the SPQ',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_SPQ_BUYER_SIG: {
    id: 'BLOCKER_SPQ_BUYER_SIG',
    compositeId: 'BLOCKER-SPQ-15008',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Buyer has not signed the SPQ',
    description: 'The buyer must acknowledge receipt by signing the SPQ (Page 4)',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_SPQ_BUYER_DATE: {
    id: 'BLOCKER_SPQ_BUYER_DATE',
    compositeId: 'BLOCKER-SPQ-15009',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Buyer signature date is missing on the SPQ',
    description: 'The buyer must date their signature on the SPQ',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  // ── SPQ warnings (retired — replaced by blockers above) ──────────────────

  WARN_SPQ_SELLER_SIGNATURE: {
    id: 'WARN_SPQ_SELLER_SIGNATURE',
    compositeId: 'WARN-SPQ-15003',
    type: 'warning',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Seller signature not found on SPQ (Signature section, Page 4)',
    description: 'The seller should sign and date the SPQ acknowledgment',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_SPQ_MISSING: {
    id: 'BLOCKER_SPQ_MISSING',
    compositeId: 'BLOCKER-SPQ-15001',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Seller Property Questionnaire (SPQ) is required but was not found',
    description: 'SPQ is mandatory for the disclosures stage',
    category: 'forms_disclosures',
    phase: 'disclosure',
    // Retired: a required document not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_SPQ_PROPERTY_ADDRESS: {
    id: 'WARN_SPQ_PROPERTY_ADDRESS',
    compositeId: 'WARN-SPQ-15002',
    type: 'warning',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Property address not identified on SPQ (Header, Page 1)',
    description: 'The property address should be clearly indicated on the SPQ form',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  BLOCKER_SPQ_YES_ITEM_MISSING_EXPLANATION: {
    id: 'BLOCKER_SPQ_YES_ITEM_MISSING_EXPLANATION',
    compositeId: 'BLOCKER-SPQ-15010',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'SPQ item marked Yes has no corresponding explanation referencing its item number',
    description: 'Every "Yes" response must have an explanation that clearly identifies which item number it answers — a generic explanation with no item-number reference does not satisfy this for any specific item',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-14',
  },

  BLOCKER_SPQ_YES_NO_NO_ANSWER_SELECTED: {
    id: 'BLOCKER_SPQ_YES_NO_NO_ANSWER_SELECTED',
    compositeId: 'BLOCKER-SPQ-15011',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'SPQ Yes/No question has no answer selected',
    description: 'Every Yes/No question on the SPQ must have exactly one of its two checkboxes marked — neither box is marked for this item',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-16',
  },

  BLOCKER_SPQ_YES_NO_BOTH_SELECTED: {
    id: 'BLOCKER_SPQ_YES_NO_BOTH_SELECTED',
    compositeId: 'BLOCKER-SPQ-15012',
    type: 'blocker',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'SPQ Yes/No question has both Yes and No marked',
    description: 'Every Yes/No question on the SPQ must have exactly one of its two checkboxes marked — both boxes appear marked for this item',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-16',
  },

  WARN_SPQ_BUYER_SIGNATURE: {
    id: 'WARN_SPQ_BUYER_SIGNATURE',
    compositeId: 'WARN-SPQ-15005',
    type: 'warning',
    formCode: 'SPQ',
    combinations: ['SPQ:*'],
    message: 'Buyer acknowledgment signature not found on SPQ (Signature section, Page 4)',
    description: 'The buyer should sign and date to acknowledge receipt of the SPQ',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── NHD form-specific (20001–21000) ───────────────────────────────────────

  BLOCKER_NHD_MISSING: {
    id: 'BLOCKER_NHD_MISSING',
    compositeId: 'BLOCKER-NHD-20001',
    type: 'blocker',
    formCode: 'NHD',
    combinations: ['NHD:*'],
    message: 'Natural Hazard Disclosure (NHD) is required but was not found',
    description: 'NHD is mandatory for the disclosures stage',
    category: 'forms_disclosures',
    phase: 'disclosure',
    // Retired: a required document not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── NHD signature blockers (20005–20006) ──────────────────────────────────

  BLOCKER_NHD_SELLER_SIG: {
    id: 'BLOCKER_NHD_SELLER_SIG',
    compositeId: 'BLOCKER-NHD-20005',
    type: 'blocker',
    formCode: 'NHD',
    combinations: ['NHD:*'],
    message: 'Seller has not signed the NHD',
    description: 'The seller must acknowledge receipt of the NHD report by signing it',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_NHD_SELLER_DATE: {
    id: 'BLOCKER_NHD_SELLER_DATE',
    compositeId: 'BLOCKER-NHD-20006',
    type: 'blocker',
    formCode: 'NHD',
    combinations: ['NHD:*'],
    message: 'Seller signature date is missing on the NHD',
    description: 'The seller must date their signature on the NHD report',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  WARN_NHD_PROPERTY_ADDRESS: {
    id: 'WARN_NHD_PROPERTY_ADDRESS',
    compositeId: 'WARN-NHD-20002',
    type: 'warning',
    formCode: 'NHD',
    combinations: ['NHD:*'],
    message: 'Property address not identified on NHD (Header, Page 1)',
    description: 'The property address should be clearly indicated on the NHD report',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_NHD_SELLER_ACKNOWLEDGMENT: {
    id: 'WARN_NHD_SELLER_ACKNOWLEDGMENT',
    compositeId: 'WARN-NHD-20003',
    type: 'warning',
    formCode: 'NHD',
    combinations: ['NHD:*'],
    message: 'Seller acknowledgment signature not found on NHD (Signature section, Page 1)',
    description: 'The seller should acknowledge receipt of the NHD report',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  WARN_NHD_HAZARD_ZONES: {
    id: 'WARN_NHD_HAZARD_ZONES',
    compositeId: 'WARN-NHD-20004',
    type: 'warning',
    formCode: 'NHD',
    combinations: ['NHD:*'],
    message: 'NHD hazard zone disclosures appear incomplete (Hazard zone checkboxes, Page 1)',
    description: 'Verify all natural hazard zone disclosures are properly completed',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── AVID signature blockers (25005–25008) ──────────────────────────────────

  BLOCKER_AVID_AGENT_SIG: {
    id: 'BLOCKER_AVID_AGENT_SIG',
    compositeId: 'BLOCKER-AVID-25005',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Agent has not signed the AVID',
    description: 'The agent must sign the AVID to affirm their inspection observations',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_AVID_AGENT_DATE: {
    id: 'BLOCKER_AVID_AGENT_DATE',
    compositeId: 'BLOCKER-AVID-25006',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Agent signature date is missing on the AVID',
    description: 'The agent must date their signature on the AVID',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_AVID_BUYER_SIG: {
    id: 'BLOCKER_AVID_BUYER_SIG',
    compositeId: 'BLOCKER-AVID-25007',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Buyer has not acknowledged receipt of the AVID',
    description: 'The buyer should sign or acknowledge receipt of the Agent Visual Inspection Disclosure',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_AVID_BUYER_DATE: {
    id: 'BLOCKER_AVID_BUYER_DATE',
    compositeId: 'BLOCKER-AVID-25008',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Buyer signature date is missing on the AVID',
    description: 'The buyer must date their acknowledgment on the AVID',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  // ── AVID warnings (retired — replaced by blockers above) ─────────────────

  WARN_AVID_PROPERTY_ADDRESS: {
    id: 'WARN_AVID_PROPERTY_ADDRESS',
    compositeId: 'WARN-AVID-25002',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Property address not identified on AVID (Header, Page 1)',
    description: 'The property address should be clearly indicated on the Agent Visual Inspection Disclosure',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-20',
  },

  WARN_AVID_AGENT_SIGNED: {
    id: 'WARN_AVID_AGENT_SIGNED',
    compositeId: 'WARN-AVID-25003',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Agent has not signed the AVID (Signature section, Page 1)',
    description: 'The agent must sign the AVID to affirm their inspection observations',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-06-20',
  },

  WARN_AVID_BUYER_ACKNOWLEDGED: {
    id: 'WARN_AVID_BUYER_ACKNOWLEDGED',
    compositeId: 'WARN-AVID-25004',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Buyer has not acknowledged receipt of the AVID (Signature section, Page 1)',
    description: 'The buyer should sign or acknowledge receipt of the Agent Visual Inspection Disclosure',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-06-20',
  },

  // ── AVID comprehensive validation blockers (25010–25040) ────────────────

  BLOCKER_AVID_WRONG_FORM: {
    id: 'BLOCKER_AVID_WRONG_FORM',
    compositeId: 'BLOCKER-AVID-25010',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Document is not a valid Agent Visual Inspection Disclosure',
    description: 'The uploaded document does not appear to be a C.A.R. Form AVID',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_PAGE_MISSING: {
    id: 'BLOCKER_AVID_PAGE_MISSING',
    compositeId: 'BLOCKER-AVID-25011',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Required AVID page is missing',
    description: 'A complete AVID requires logical pages 1, 2, and 3',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_PAGE_DUPLICATE: {
    id: 'BLOCKER_AVID_PAGE_DUPLICATE',
    compositeId: 'BLOCKER-AVID-25012',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Duplicate AVID page detected',
    description: 'A logical AVID page appears more than once, replacing a required page',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_MIXED_REVISION: {
    id: 'BLOCKER_AVID_MIXED_REVISION',
    compositeId: 'BLOCKER-AVID-25013',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Mixed AVID revisions detected across pages',
    description: 'Different AVID revision dates are present in the same three-page form',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_PROPERTY_MISSING: {
    id: 'BLOCKER_AVID_PROPERTY_MISSING',
    compositeId: 'BLOCKER-AVID-25014',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Property identification missing on AVID',
    description: 'Property address, city, or county is missing from the AVID',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_PROPERTY_MISMATCH: {
    id: 'BLOCKER_AVID_PROPERTY_MISMATCH',
    compositeId: 'BLOCKER-AVID-25015',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'AVID property address does not match transaction',
    description: 'The property address on the AVID does not match the transaction property address',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_BROKER_FIRM_MISSING: {
    id: 'BLOCKER_AVID_BROKER_FIRM_MISSING',
    compositeId: 'BLOCKER-AVID-25016',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Inspecting broker firm name missing on AVID',
    description: 'The broker firm that performed the inspection must be identified',
    category: 'parties',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_BROKER_FIRM_MISMATCH: {
    id: 'BLOCKER_AVID_BROKER_FIRM_MISMATCH',
    compositeId: 'BLOCKER-AVID-25017',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Broker firm mismatch across AVID pages',
    description: 'The broker firm on page 1 does not match the broker firm on page 3',
    category: 'parties',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_UNIT_NUMBER_MISSING: {
    id: 'BLOCKER_AVID_UNIT_NUMBER_MISSING',
    compositeId: 'BLOCKER-AVID-25018',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Unit number missing on multi-unit AVID',
    description: 'The AVID applies to specific units but the unit identifier is missing',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_UNIT_NUMBER_MISMATCH: {
    id: 'BLOCKER_AVID_UNIT_NUMBER_MISMATCH',
    compositeId: 'BLOCKER-AVID-25019',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Unit number mismatch across AVID pages',
    description: 'The unit identifiers are inconsistent across AVID pages',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_P1_BUYER_INITIALS_MISSING: {
    id: 'BLOCKER_AVID_P1_BUYER_INITIALS_MISSING',
    compositeId: 'BLOCKER-AVID-25020',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Required buyer initials missing on AVID Page 1',
    description: 'Buyer initials are required in the footer of AVID page 1',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_P2_BUYER_INITIALS_MISSING: {
    id: 'BLOCKER_AVID_P2_BUYER_INITIALS_MISSING',
    compositeId: 'BLOCKER-AVID-25021',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Required buyer initials missing on AVID Page 2',
    description: 'Buyer initials are required in the footer of AVID page 2',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_AREA_OBSERVATION_MISSING: {
    id: 'BLOCKER_AVID_AREA_OBSERVATION_MISSING',
    compositeId: 'BLOCKER-AVID-25022',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Required area observation missing on AVID',
    description: 'An applicable area has no observation recorded',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_ADDENDUM_MISSING: {
    id: 'BLOCKER_AVID_ADDENDUM_MISSING',
    compositeId: 'BLOCKER-AVID-25023',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Referenced AVID addendum not present',
    description: '"See Addendum" is checked but the referenced addendum is not included',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_INSPECTOR_NAME_MISSING: {
    id: 'BLOCKER_AVID_INSPECTOR_NAME_MISSING',
    compositeId: 'BLOCKER-AVID-25024',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Inspector name missing on AVID certification',
    description: 'The name of the individual agent or broker who performed the inspection is required',
    category: 'parties',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_INSPECTION_DATE_MISSING: {
    id: 'BLOCKER_AVID_INSPECTION_DATE_MISSING',
    compositeId: 'BLOCKER-AVID-25025',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Inspection date missing on AVID',
    description: 'The date of the visual inspection is required',
    category: 'dates',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_INSPECTION_TIME_MISSING: {
    id: 'BLOCKER_AVID_INSPECTION_TIME_MISSING',
    compositeId: 'BLOCKER-AVID-25026',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Inspection time missing on AVID',
    description: 'The time of the visual inspection is required',
    category: 'dates',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_WEATHER_MISSING: {
    id: 'BLOCKER_AVID_WEATHER_MISSING',
    compositeId: 'BLOCKER-AVID-25027',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Weather conditions missing on AVID',
    description: 'Weather conditions during the inspection are required',
    category: 'dates',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_AGENT_SIGNATURE_MISSING: {
    id: 'BLOCKER_AVID_AGENT_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-AVID-25028',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Agent signature missing on AVID inspection certification',
    description: 'The inspecting agent or broker must sign the certification on page 3',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_AGENT_SIGNATURE_DATE_MISSING: {
    id: 'BLOCKER_AVID_AGENT_SIGNATURE_DATE_MISSING',
    compositeId: 'BLOCKER-AVID-25029',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Agent signature date missing on AVID',
    description: 'The date next to the inspecting agent signature is required',
    category: 'dates',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_BUYER_SIGNATURE_MISSING: {
    id: 'BLOCKER_AVID_BUYER_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-AVID-25030',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Buyer acknowledgment signature missing on AVID',
    description: 'Each buyer must sign to acknowledge receipt of the AVID',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_BUYER_SIGNATURE_DATE_MISSING: {
    id: 'BLOCKER_AVID_BUYER_SIGNATURE_DATE_MISSING',
    compositeId: 'BLOCKER-AVID-25031',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Buyer acknowledgment date missing on AVID',
    description: 'The date next to each buyer acknowledgment signature is required',
    category: 'dates',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_AVID_DATE_CHRONOLOGY_INVALID: {
    id: 'BLOCKER_AVID_DATE_CHRONOLOGY_INVALID',
    compositeId: 'BLOCKER-AVID-25032',
    type: 'blocker',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Invalid date chronology on AVID',
    description: 'Agent signature date precedes inspection date or buyer acknowledgement predates agent signature',
    category: 'dates',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  // ── AVID comprehensive validation warnings (25040–25050) ───────────────

  WARN_AVID_MANUAL_REVIEW: {
    id: 'WARN_AVID_MANUAL_REVIEW',
    compositeId: 'WARN-AVID-25040',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'AVID requires manual review',
    description: 'The AVID has conditions that require manual review by a transaction coordinator',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_AVID_APPLICABLE_AREA_UNKNOWN: {
    id: 'WARN_AVID_APPLICABLE_AREA_UNKNOWN',
    compositeId: 'WARN-AVID-25041',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Some applicable areas may need observations',
    description: 'Areas that may exist have no observation and property context is unavailable',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_AVID_GENERIC_OBSERVATIONS: {
    id: 'WARN_AVID_GENERIC_OBSERVATIONS',
    compositeId: 'WARN-AVID-25042',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['AVID:*'],
    message: 'Repeated generic language detected in AVID observations',
    description: 'Multiple inspection areas contain substantially identical generic language',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  // ── BHIA comprehensive validation (26010–26030) ─────────────────────────────

  BLOCKER_BHIA_WRONG_FORM: {
    id: 'BLOCKER_BHIA_WRONG_FORM',
    compositeId: 'BLOCKER-BHIA-26010',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'Uploaded page is not C.A.R. Form BHIA',
    description: 'The detected page identity does not match the expected Buyer Homeowners\' Insurance Advisory',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_WRONG_PAGE: {
    id: 'BLOCKER_BHIA_WRONG_PAGE',
    compositeId: 'BLOCKER-BHIA-26011',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'BHIA page label does not match expected page 1 of 1',
    description: 'The detected logical page number or label does not match the expected BHIA page',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_PAGE_MISSING: {
    id: 'BLOCKER_BHIA_PAGE_MISSING',
    compositeId: 'BLOCKER-BHIA-26012',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'BHIA page not found in document',
    description: 'A page labeled as BHIA was expected but not found in the document',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_CONTENT_INCOMPLETE: {
    id: 'BLOCKER_BHIA_CONTENT_INCOMPLETE',
    compositeId: 'BLOCKER-BHIA-26013',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'BHIA content is materially incomplete or cropped',
    description: 'A material portion of the BHIA page is missing or cropped',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_ACKNOWLEDGMENT_MISSING: {
    id: 'BLOCKER_BHIA_ACKNOWLEDGMENT_MISSING',
    compositeId: 'BLOCKER-BHIA-26014',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'BHIA Buyer acknowledgment section is missing',
    description: 'The acknowledgment text and signature area are not present on the BHIA',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_BUYER_1_SIGNATURE_MISSING: {
    id: 'BLOCKER_BHIA_BUYER_1_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-BHIA-26015',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'Buyer 1 signature missing on BHIA',
    description: 'Buyer 1 must sign the BHIA acknowledgment',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_BUYER_1_DATE_MISSING: {
    id: 'BLOCKER_BHIA_BUYER_1_DATE_MISSING',
    compositeId: 'BLOCKER-BHIA-26016',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'Buyer 1 signature date missing on BHIA',
    description: 'Buyer 1 must date their signature on the BHIA',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_BUYER_2_SIGNATURE_MISSING: {
    id: 'BLOCKER_BHIA_BUYER_2_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-BHIA-26017',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'Buyer 2 signature missing on BHIA',
    description: 'Buyer 2 must sign the BHIA acknowledgment',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_BUYER_2_DATE_MISSING: {
    id: 'BLOCKER_BHIA_BUYER_2_DATE_MISSING',
    compositeId: 'BLOCKER-BHIA-26018',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'Buyer 2 signature date missing on BHIA',
    description: 'Buyer 2 must date their signature on the BHIA',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_BHIA_BUYER_SIGNER_MISMATCH: {
    id: 'BLOCKER_BHIA_BUYER_SIGNER_MISMATCH',
    compositeId: 'BLOCKER-BHIA-26019',
    type: 'blocker',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'BHIA Buyer signer does not match the expected Buyer',
    description: 'The signer identity on the BHIA does not match the expected Buyer from transaction context',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  // ── BHIA warnings ─────────────────────────────────────────────────────────

  WARN_BHIA_BUYER_COUNT_UNKNOWN: {
    id: 'WARN_BHIA_BUYER_COUNT_UNKNOWN',
    compositeId: 'WARN-BHIA-26025',
    type: 'warning',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'Buyer count is unknown — cannot confirm all required signatures are present',
    description: 'Transaction context did not provide a required Buyer count. Evaluate visually.',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_BHIA_SIGNATURE_UNREADABLE: {
    id: 'WARN_BHIA_SIGNATURE_UNREADABLE',
    compositeId: 'WARN-BHIA-26026',
    type: 'warning',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'BHIA signature is unreadable — manual review required',
    description: 'A signature mark is present but the signer name cannot be read',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_BHIA_SIGNER_IDENTITY_UNKNOWN: {
    id: 'WARN_BHIA_SIGNER_IDENTITY_UNKNOWN',
    compositeId: 'WARN-BHIA-26027',
    type: 'warning',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'Cannot determine if BHIA signer matches expected Buyer',
    description: 'Signature present but identity cannot be confirmed against expected Buyer names',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_BHIA_MANUAL_REVIEW: {
    id: 'WARN_BHIA_MANUAL_REVIEW',
    compositeId: 'WARN-BHIA-26028',
    type: 'warning',
    formCode: 'BHIA',
    combinations: ['BHIA:*'],
    message: 'BHIA requires manual review',
    description: 'The BHIA has conditions that require manual review by a transaction coordinator',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  // ── WFA blockers (27001–27028) ───────────────────────────────────────────

  BLOCKER_WFA_WRONG_FORM: {
    id: 'BLOCKER_WFA_WRONG_FORM',
    compositeId: 'BLOCKER-WFA-27001',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Uploaded page is not C.A.R. Form WFA',
    description: 'The uploaded document is not the Wire Fraud and Electronic Funds Transfer Advisory',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_WRONG_PAGE: {
    id: 'BLOCKER_WFA_WRONG_PAGE',
    compositeId: 'BLOCKER-WFA-27002',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Uploaded page is not the correct WFA page',
    description: 'The WFA page number does not match the expected single-page form',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_PAGE_MISSING: {
    id: 'BLOCKER_WFA_PAGE_MISSING',
    compositeId: 'BLOCKER-WFA-27003',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA page not found in document',
    description: 'The WFA page was expected but not found in the uploaded document',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_CONTENT_INCOMPLETE: {
    id: 'BLOCKER_WFA_CONTENT_INCOMPLETE',
    compositeId: 'BLOCKER-WFA-27004',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'A material portion of the WFA page is missing or cropped',
    description: 'The document is incomplete — advisory content, recommendations, or acknowledgment section is missing',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_ACKNOWLEDGMENT_MISSING: {
    id: 'BLOCKER_WFA_ACKNOWLEDGMENT_MISSING',
    compositeId: 'BLOCKER-WFA-27005',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA acknowledgment and signature section is missing',
    description: 'The acknowledgment text and signature area are not present on the WFA',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_BUYER_TENANT_1_SIGNATURE_MISSING: {
    id: 'BLOCKER_WFA_BUYER_TENANT_1_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-WFA-27006',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Buyer/Tenant 1 signature missing on WFA',
    description: 'The first Buyer/Tenant must sign the WFA acknowledgment',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_BUYER_TENANT_1_DATE_MISSING: {
    id: 'BLOCKER_WFA_BUYER_TENANT_1_DATE_MISSING',
    compositeId: 'BLOCKER-WFA-27007',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Buyer/Tenant 1 signature date missing on WFA',
    description: 'The first Buyer/Tenant must date their signature on the WFA',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_BUYER_TENANT_2_SIGNATURE_MISSING: {
    id: 'BLOCKER_WFA_BUYER_TENANT_2_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-WFA-27008',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Buyer/Tenant 2 signature missing on WFA',
    description: 'The second Buyer/Tenant must sign the WFA acknowledgment when required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_BUYER_TENANT_2_DATE_MISSING: {
    id: 'BLOCKER_WFA_BUYER_TENANT_2_DATE_MISSING',
    compositeId: 'BLOCKER-WFA-27009',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Buyer/Tenant 2 signature date missing on WFA',
    description: 'The second Buyer/Tenant must date their signature on the WFA when required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_BUYER_TENANT_SIGNER_MISMATCH: {
    id: 'BLOCKER_WFA_BUYER_TENANT_SIGNER_MISMATCH',
    compositeId: 'BLOCKER-WFA-27010',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA Buyer/Tenant acknowledgment signer does not match the expected party',
    description: 'The signer on the Buyer/Tenant line does not match the expected party name',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_SELLER_HOUSING_PROVIDER_1_SIGNATURE_MISSING: {
    id: 'BLOCKER_WFA_SELLER_HOUSING_PROVIDER_1_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-WFA-27011',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Seller/Housing Provider 1 signature missing on WFA',
    description: 'The first Seller/Housing Provider must sign the WFA acknowledgment',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_SELLER_HOUSING_PROVIDER_1_DATE_MISSING: {
    id: 'BLOCKER_WFA_SELLER_HOUSING_PROVIDER_1_DATE_MISSING',
    compositeId: 'BLOCKER-WFA-27012',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Seller/Housing Provider 1 signature date missing on WFA',
    description: 'The first Seller/Housing Provider must date their signature on the WFA',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_SELLER_HOUSING_PROVIDER_2_SIGNATURE_MISSING: {
    id: 'BLOCKER_WFA_SELLER_HOUSING_PROVIDER_2_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-WFA-27013',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Seller/Housing Provider 2 signature missing on WFA',
    description: 'The second Seller/Housing Provider must sign the WFA acknowledgment when required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_SELLER_HOUSING_PROVIDER_2_DATE_MISSING: {
    id: 'BLOCKER_WFA_SELLER_HOUSING_PROVIDER_2_DATE_MISSING',
    compositeId: 'BLOCKER-WFA-27014',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Seller/Housing Provider 2 signature date missing on WFA',
    description: 'The second Seller/Housing Provider must date their signature on the WFA when required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  BLOCKER_WFA_SELLER_HOUSING_PROVIDER_SIGNER_MISMATCH: {
    id: 'BLOCKER_WFA_SELLER_HOUSING_PROVIDER_SIGNER_MISMATCH',
    compositeId: 'BLOCKER-WFA-27015',
    type: 'blocker',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA Seller/Housing Provider acknowledgment signer does not match the expected party',
    description: 'The signer on the Seller/Housing Provider line does not match the expected party name',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_WFA_BUYER_TENANT_COUNT_UNKNOWN: {
    id: 'WARN_WFA_BUYER_TENANT_COUNT_UNKNOWN',
    compositeId: 'WARN-WFA-27016',
    type: 'warning',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA Buyer/Tenant count unknown',
    description: 'Transaction context did not provide a required Buyer/Tenant count',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_WFA_SELLER_HOUSING_PROVIDER_COUNT_UNKNOWN: {
    id: 'WARN_WFA_SELLER_HOUSING_PROVIDER_COUNT_UNKNOWN',
    compositeId: 'WARN-WFA-27017',
    type: 'warning',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA Seller/Housing Provider count unknown',
    description: 'Transaction context did not provide a required Seller/Housing Provider count',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_WFA_SIGNATURE_UNREADABLE: {
    id: 'WARN_WFA_SIGNATURE_UNREADABLE',
    compositeId: 'WARN-WFA-27018',
    type: 'warning',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA signature is unreadable — manual review required',
    description: 'A signature mark is present but the signer name cannot be read',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_WFA_SIGNER_IDENTITY_UNKNOWN: {
    id: 'WARN_WFA_SIGNER_IDENTITY_UNKNOWN',
    compositeId: 'WARN-WFA-27019',
    type: 'warning',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'Cannot determine if WFA signer matches expected party',
    description: 'Signature present but identity cannot be confirmed against expected party names',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  WARN_WFA_MANUAL_REVIEW: {
    id: 'WARN_WFA_MANUAL_REVIEW',
    compositeId: 'WARN-WFA-27020',
    type: 'warning',
    formCode: 'WFA',
    combinations: ['WFA:*'],
    message: 'WFA requires manual review',
    description: 'The WFA has conditions that require manual review by a transaction coordinator',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-26',
  },

  // ── BIA comprehensive validation (28001–28016) ──────────────────────────────

  BLOCKER_BIA_WRONG_FORM: {
    id: 'BLOCKER_BIA_WRONG_FORM',
    compositeId: 'BLOCKER-BIA-28001',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Uploaded document is not C.A.R. Form BIA',
    description: 'The uploaded document does not appear to be the Buyer\'s Investigation Advisory',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_PAGE_MISSING: {
    id: 'BLOCKER_BIA_PAGE_MISSING',
    compositeId: 'BLOCKER-BIA-28002',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Required BIA page is missing',
    description: 'A complete BIA requires logical pages 1 and 2',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_PAGE_DUPLICATE: {
    id: 'BLOCKER_BIA_PAGE_DUPLICATE',
    compositeId: 'BLOCKER-BIA-28003',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Duplicate BIA page detected',
    description: 'A logical BIA page appears more than once, replacing a required page',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_WRONG_PAGE_ORDER: {
    id: 'BLOCKER_BIA_WRONG_PAGE_ORDER',
    compositeId: 'BLOCKER-BIA-28004',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'BIA pages are in the wrong order',
    description: 'Logical BIA page 1 does not appear before logical BIA page 2',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_MIXED_REVISION: {
    id: 'BLOCKER_BIA_MIXED_REVISION',
    compositeId: 'BLOCKER-BIA-28005',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Mixed BIA revisions detected across pages',
    description: 'Different BIA revision dates are present in the same two-page form',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_CONTENT_INCOMPLETE: {
    id: 'BLOCKER_BIA_CONTENT_INCOMPLETE',
    compositeId: 'BLOCKER-BIA-28006',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'BIA content is materially incomplete or cropped',
    description: 'A material portion of the BIA is missing or cropped',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_ACKNOWLEDGMENT_MISSING: {
    id: 'BLOCKER_BIA_ACKNOWLEDGMENT_MISSING',
    compositeId: 'BLOCKER-BIA-28007',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'BIA Buyer acknowledgment section is missing',
    description: 'The acknowledgment text and signature area are not present on the BIA',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_BUYER_1_SIGNATURE_MISSING: {
    id: 'BLOCKER_BIA_BUYER_1_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-BIA-28008',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer 1 signature missing on BIA',
    description: 'Buyer 1 must sign the BIA acknowledgment',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_BUYER_1_DATE_MISSING: {
    id: 'BLOCKER_BIA_BUYER_1_DATE_MISSING',
    compositeId: 'BLOCKER-BIA-28009',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer 1 signature date missing on BIA',
    description: 'Buyer 1 must date their signature on the BIA',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_BUYER_2_SIGNATURE_MISSING: {
    id: 'BLOCKER_BIA_BUYER_2_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-BIA-28010',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer 2 signature missing on BIA',
    description: 'Buyer 2 must sign the BIA acknowledgment when required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_BUYER_2_DATE_MISSING: {
    id: 'BLOCKER_BIA_BUYER_2_DATE_MISSING',
    compositeId: 'BLOCKER-BIA-28011',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer 2 signature date missing on BIA',
    description: 'Buyer 2 must date their signature on the BIA when required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_BIA_BUYER_SIGNER_MISMATCH: {
    id: 'BLOCKER_BIA_BUYER_SIGNER_MISMATCH',
    compositeId: 'BLOCKER-BIA-28012',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'BIA Buyer signer does not match the expected Buyer',
    description: 'The signer identity on the BIA does not match the expected Buyer from transaction context',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_BIA_BUYER_COUNT_UNKNOWN: {
    id: 'WARN_BIA_BUYER_COUNT_UNKNOWN',
    compositeId: 'WARN-BIA-28013',
    type: 'warning',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer count is unknown — cannot confirm all required signatures are present',
    description: 'Transaction context did not provide a required Buyer count. Evaluate visually.',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_BIA_SIGNATURE_UNREADABLE: {
    id: 'WARN_BIA_SIGNATURE_UNREADABLE',
    compositeId: 'WARN-BIA-28014',
    type: 'warning',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'BIA signature is unreadable — manual review required',
    description: 'A signature mark is present but the signer name cannot be read',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_BIA_SIGNER_IDENTITY_UNKNOWN: {
    id: 'WARN_BIA_SIGNER_IDENTITY_UNKNOWN',
    compositeId: 'WARN-BIA-28015',
    type: 'warning',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Cannot determine if BIA signer matches expected Buyer',
    description: 'Signature present but identity cannot be confirmed against expected Buyer names',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_BIA_MANUAL_REVIEW: {
    id: 'WARN_BIA_MANUAL_REVIEW',
    compositeId: 'WARN-BIA-28016',
    type: 'warning',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'BIA requires manual review',
    description: 'The BIA has conditions that require manual review by a transaction coordinator',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  // ── BIA legacy signature blockers (retired — replaced by 28008–28012) ──────

  BLOCKER_BIA_BUYER_SIG: {
    id: 'BLOCKER_BIA_BUYER_SIG',
    compositeId: 'BLOCKER-BIA-30001',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer has not signed the BIA',
    description: 'The buyer must acknowledge the BIA by initialing or signing',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_BIA_BUYER_DATE: {
    id: 'BLOCKER_BIA_BUYER_DATE',
    compositeId: 'BLOCKER-BIA-30002',
    type: 'blocker',
    formCode: 'BIA',
    combinations: ['BIA:*'],
    message: 'Buyer signature date is missing on the BIA',
    description: 'The buyer must date their signature on the BIA',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  // ── SCO signature blockers (35008–35009) ───────────────────────────────────

  BLOCKER_SCO_OFFEROR_SIG: {
    id: 'BLOCKER_SCO_OFFEROR_SIG',
    compositeId: 'BLOCKER-SCO-35008',
    type: 'blocker',
    formCode: 'SCO',
    combinations: ['SCO:*', 'SMCO:*'],
    message: 'Offeror has not signed the counter offer',
    description: 'The offeror (seller on SCO, buyer on BCO) must sign Section 4',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_SCO_ACCEPTOR_SIG: {
    id: 'BLOCKER_SCO_ACCEPTOR_SIG',
    compositeId: 'BLOCKER-SCO-35009',
    type: 'blocker',
    formCode: 'SCO',
    combinations: ['SCO:*', 'SMCO:*'],
    message: 'Acceptor has not signed the counter offer',
    description: 'The acceptor (buyer on SCO, seller on BCO) must sign Section 5',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  // ── BCO signature blockers (35010–35011) ───────────────────────────────────

  BLOCKER_BCO_OFFEROR_SIG: {
    id: 'BLOCKER_BCO_OFFEROR_SIG',
    compositeId: 'BLOCKER-BCO-35010',
    type: 'blocker',
    formCode: 'BCO',
    combinations: ['BCO:*', 'BMCO:*'],
    message: 'Offeror has not signed the counter offer',
    description: 'The offeror (seller on SCO, buyer on BCO) must sign Section 4',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  BLOCKER_BCO_ACCEPTOR_SIG: {
    id: 'BLOCKER_BCO_ACCEPTOR_SIG',
    compositeId: 'BLOCKER-BCO-35011',
    type: 'blocker',
    formCode: 'BCO',
    combinations: ['BCO:*', 'BMCO:*'],
    message: 'Acceptor has not signed the counter offer',
    description: 'The acceptor (buyer on SCO, seller on BCO) must sign Section 5',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-11',
  },

  WARN_CROSS_PROPERTY_ADDRESS: {
    id: 'WARN_CROSS_PROPERTY_ADDRESS',
    compositeId: 'WARN-CROSS-11001',
    type: 'warning',
    formCode: 'CROSS',
    combinations: ['RPA:*', 'TDS:*', 'SPQ:*', 'NHD:*'],
    message: 'Property address differs across RPA and disclosure forms',
    description: 'The property address on the RPA should match the address on the TDS, SPQ, and NHD forms',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-29',
  },

  WARN_CROSS_PROPERTY_CITY: {
    id: 'WARN_CROSS_PROPERTY_CITY',
    compositeId: 'WARN-CROSS-11002',
    type: 'warning',
    formCode: 'CROSS',
    combinations: ['RPA:*', 'TDS:*', 'SPQ:*', 'NHD:*'],
    message: 'Property city differs across RPA and disclosure forms',
    description: 'The property city on the RPA should match the city on the TDS, SPQ, and NHD forms',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-05-29',
  },

  // ── Expected companion forms (progressive upload warnings) ────────────────

  WARN_MISSING_AVID_DISCLOSURES: {
    id: 'WARN_MISSING_AVID_DISCLOSURES',
    compositeId: 'WARN-TDS-10003',
    type: 'warning',
    formCode: 'AVID',
    combinations: ['TDS:*', 'AVID:'],
    message: 'Agent Visual Inspection Disclosure (AVID) not yet uploaded',
    description: 'AVID is expected alongside the disclosure package',
    category: 'forms_disclosures',
    phase: 'disclosure',
    // Retired: a required document not yet uploaded is a checklist concern
    // (TransactionFormTemplatesService), never a validation blocker.
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-05-24',
  },

  // ── Stage-level rules (50001–51000) ─────────────────────────────────────────

  WARN_DISCLOSURES_SIGNATURES: {
    id: 'WARN_DISCLOSURES_SIGNATURES',
    compositeId: 'WARN-DISCLOSURES-50001',
    type: 'warning',
    formCode: 'STAGE',
    combinations: ['TDS:*', 'SPQ:*', 'NHD:*'],
    message: 'One or more required disclosure forms are missing signatures or acknowledgments',
    description: 'Review and collect all signatures: TDS (seller + buyer), SPQ (seller + buyer), NHD (seller acknowledgment)',
    category: 'signatures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-06-20',
  },

  WARN_DISCLOSURES_INCOMPLETE: {
    id: 'WARN_DISCLOSURES_INCOMPLETE',
    compositeId: 'WARN-DISCLOSURES-50002',
    type: 'warning',
    formCode: 'STAGE',
    combinations: ['TDS:*', 'SPQ:*', 'NHD:*'],
    message: 'Disclosure package appears incomplete — review all uploaded forms',
    description: 'Ensure all sections are completed on each uploaded disclosure form before advancing',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: false,
    introducedBy: 'system',
    dateAdded: '2026-06-20',
  },

  WARN_DISCLOSURES_DEADLINES: {
    id: 'WARN_DISCLOSURES_DEADLINES',
    compositeId: 'WARN-DISCLOSURES-50003',
    type: 'warning',
    formCode: 'STAGE',
    combinations: ['RPA:*'],
    message: 'Disclosure due period is not specified in the RPA',
    description: 'The RPA should specify the number of days for disclosures due to track disclosure deadlines',
    category: 'dates',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-06-20',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FHDA — Fair Housing and Discrimination Advisory  (29001–29020)
  // ═══════════════════════════════════════════════════════════════════════════════

  BLOCKER_FHDA_WRONG_FORM: {
    id: 'BLOCKER_FHDA_WRONG_FORM',
    compositeId: 'BLOCKER-FHDA-29001',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Uploaded document is not C.A.R. Form FHDA',
    description: 'The uploaded document does not match the Fair Housing and Discrimination Advisory form identity',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_WRONG_PAGE: {
    id: 'BLOCKER_FHDA_WRONG_PAGE',
    compositeId: 'BLOCKER-FHDA-29002',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA page label does not match expected page',
    description: 'One or more FHDA logical page labels do not match pages 1 of 2 and 2 of 2',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_PAGE_MISSING: {
    id: 'BLOCKER_FHDA_PAGE_MISSING',
    compositeId: 'BLOCKER-FHDA-29003',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Required FHDA page is missing',
    description: 'One or more required FHDA pages are not present in the uploaded document',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_CONTENT_INCOMPLETE: {
    id: 'BLOCKER_FHDA_CONTENT_INCOMPLETE',
    compositeId: 'BLOCKER-FHDA-29004',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA content is materially incomplete or cropped',
    description: 'A material portion of the FHDA page is missing, cropped, or unreadable',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_MIXED_REVISION: {
    id: 'BLOCKER_FHDA_MIXED_REVISION',
    compositeId: 'BLOCKER-FHDA-29005',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Mixed FHDA revisions detected across pages',
    description: 'The FHDA pages contain inconsistent form revisions or titles',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_PROTECTED_CLASSES_TABLE_MISSING: {
    id: 'BLOCKER_FHDA_PROTECTED_CLASSES_TABLE_MISSING',
    compositeId: 'BLOCKER-FHDA-29006',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA protected classes table is missing from page 2',
    description: 'The protected classes/characteristics table (sections 9E–9O) is required on page 2',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_ACKNOWLEDGMENT_MISSING: {
    id: 'BLOCKER_FHDA_ACKNOWLEDGMENT_MISSING',
    compositeId: 'BLOCKER-FHDA-29007',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA acknowledgment and signature section is missing',
    description: 'The acknowledgment text and signature area are not present on the FHDA',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_BUYER_TENANT_1_SIGNATURE_MISSING: {
    id: 'BLOCKER_FHDA_BUYER_TENANT_1_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-FHDA-29008',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Buyer/Tenant 1 signature missing on FHDA',
    description: 'The first Buyer/Tenant signature line on the FHDA acknowledgment is not signed',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_BUYER_TENANT_1_DATE_MISSING: {
    id: 'BLOCKER_FHDA_BUYER_TENANT_1_DATE_MISSING',
    compositeId: 'BLOCKER-FHDA-29009',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Buyer/Tenant 1 signature date missing on FHDA',
    description: 'The first Buyer/Tenant signature on the FHDA is not dated',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_BUYER_TENANT_2_SIGNATURE_MISSING: {
    id: 'BLOCKER_FHDA_BUYER_TENANT_2_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-FHDA-29010',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Buyer/Tenant 2 signature missing on FHDA',
    description: 'The second Buyer/Tenant signature line on the FHDA acknowledgment is not signed',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_BUYER_TENANT_2_DATE_MISSING: {
    id: 'BLOCKER_FHDA_BUYER_TENANT_2_DATE_MISSING',
    compositeId: 'BLOCKER-FHDA-29011',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Buyer/Tenant 2 signature date missing on FHDA',
    description: 'The second Buyer/Tenant signature on the FHDA is not dated',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_BUYER_TENANT_SIGNER_MISMATCH: {
    id: 'BLOCKER_FHDA_BUYER_TENANT_SIGNER_MISMATCH',
    compositeId: 'BLOCKER-FHDA-29012',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA Buyer/Tenant acknowledgment signer does not match the expected party',
    description: 'The signer on a Buyer/Tenant line does not match the expected Buyer/Tenant name from transaction context',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_1_SIGNATURE_MISSING: {
    id: 'BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_1_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-FHDA-29013',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Seller/Housing Provider 1 signature missing on FHDA',
    description: 'The first Seller/Housing Provider signature line on the FHDA acknowledgment is not signed',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_1_DATE_MISSING: {
    id: 'BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_1_DATE_MISSING',
    compositeId: 'BLOCKER-FHDA-29014',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Seller/Housing Provider 1 signature date missing on FHDA',
    description: 'The first Seller/Housing Provider signature on the FHDA is not dated',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_2_SIGNATURE_MISSING: {
    id: 'BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_2_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-FHDA-29015',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Seller/Housing Provider 2 signature missing on FHDA',
    description: 'The second Seller/Housing Provider signature line on the FHDA acknowledgment is not signed',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_2_DATE_MISSING: {
    id: 'BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_2_DATE_MISSING',
    compositeId: 'BLOCKER-FHDA-29016',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Seller/Housing Provider 2 signature date missing on FHDA',
    description: 'The second Seller/Housing Provider signature on the FHDA is not dated',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_SIGNER_MISMATCH: {
    id: 'BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_SIGNER_MISMATCH',
    compositeId: 'BLOCKER-FHDA-29017',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA Seller/Housing Provider acknowledgment signer does not match the expected party',
    description: 'The signer on a Seller/Housing Provider line does not match the expected Seller/Housing Provider name from transaction context',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SIGNATURE_UNREADABLE: {
    id: 'BLOCKER_FHDA_SIGNATURE_UNREADABLE',
    compositeId: 'BLOCKER-FHDA-29018',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA signature is unreadable — manual review required',
    description: 'A signature is present but the signer identity cannot be determined for name-matching',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SIGNER_IDENTITY_UNKNOWN: {
    id: 'BLOCKER_FHDA_SIGNER_IDENTITY_UNKNOWN',
    compositeId: 'BLOCKER-FHDA-29019',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Cannot determine if FHDA signer matches expected party',
    description: 'A signature is present but the signer identity cannot be compared with expected party names',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_MANUAL_REVIEW: {
    id: 'BLOCKER_FHDA_MANUAL_REVIEW',
    compositeId: 'BLOCKER-FHDA-29020',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'FHDA requires manual review',
    description: 'The FHDA has conditions that require manual review by a transaction coordinator',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_BUYER_TENANT_COUNT_UNKNOWN: {
    id: 'BLOCKER_FHDA_BUYER_TENANT_COUNT_UNKNOWN',
    compositeId: 'BLOCKER-FHDA-29021',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Buyer/Tenant count is unknown on FHDA',
    description: 'Transaction context did not provide a required Buyer/Tenant count — visual review required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_COUNT_UNKNOWN: {
    id: 'BLOCKER_FHDA_SELLER_HOUSING_PROVIDER_COUNT_UNKNOWN',
    compositeId: 'BLOCKER-FHDA-29022',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Seller/Housing Provider count is unknown on FHDA',
    description: 'Transaction context did not provide a required Seller/Housing Provider count — visual review required',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_FHDA_TRANSACTION_TYPE_UNKNOWN: {
    id: 'BLOCKER_FHDA_TRANSACTION_TYPE_UNKNOWN',
    compositeId: 'BLOCKER-FHDA-29023',
    type: 'blocker',
    formCode: 'FHDA',
    combinations: ['FHDA:*'],
    message: 'Transaction type is unknown on FHDA',
    description: 'Transaction context did not specify whether this is a purchase or rental — role labels cannot be resolved',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CCPA — California Consumer Privacy Act Advisory  (36001–36014)
  // ═══════════════════════════════════════════════════════════════════════════════

  BLOCKER_CCPA_WRONG_FORM: {
    id: 'BLOCKER_CCPA_WRONG_FORM',
    compositeId: 'BLOCKER-CCPA-36001',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'Uploaded document is not C.A.R. Form CCPA',
    description: 'The document must be the California Consumer Privacy Act Advisory, Disclosure and Notice',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_PAGE_MISSING: {
    id: 'BLOCKER_CCPA_PAGE_MISSING',
    compositeId: 'BLOCKER-CCPA-36002',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'CCPA page 1 of 1 is missing or incomplete',
    description: 'The complete one-page CCPA advisory must be present',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_CONTENT_INCOMPLETE: {
    id: 'BLOCKER_CCPA_CONTENT_INCOMPLETE',
    compositeId: 'BLOCKER-CCPA-36003',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'CCPA advisory content is incomplete',
    description: 'A material portion of the CCPA advisory is missing or cropped',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_ACKNOWLEDGMENT_MISSING: {
    id: 'BLOCKER_CCPA_ACKNOWLEDGMENT_MISSING',
    compositeId: 'BLOCKER-CCPA-36004',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'CCPA acknowledgment section is missing',
    description: 'The acknowledging-party signature section must be present',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_PARTY_1_SIGNATURE_MISSING: {
    id: 'BLOCKER_CCPA_PARTY_1_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-CCPA-36005',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'Acknowledging party 1 has not signed the CCPA',
    description: 'The first required CCPA acknowledgment signature is missing',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_PARTY_1_DATE_MISSING: {
    id: 'BLOCKER_CCPA_PARTY_1_DATE_MISSING',
    compositeId: 'BLOCKER-CCPA-36006',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'Acknowledging party 1 signature date is missing on CCPA',
    description: 'The first required CCPA signature must have a corresponding date',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_PARTY_2_SIGNATURE_MISSING: {
    id: 'BLOCKER_CCPA_PARTY_2_SIGNATURE_MISSING',
    compositeId: 'BLOCKER-CCPA-36007',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'Acknowledging party 2 has not signed the CCPA',
    description: 'The second required CCPA acknowledgment signature is missing',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_PARTY_2_DATE_MISSING: {
    id: 'BLOCKER_CCPA_PARTY_2_DATE_MISSING',
    compositeId: 'BLOCKER-CCPA-36008',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'Acknowledging party 2 signature date is missing on CCPA',
    description: 'The second required CCPA signature must have a corresponding date',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_SIGNER_MISMATCH: {
    id: 'BLOCKER_CCPA_SIGNER_MISMATCH',
    compositeId: 'BLOCKER-CCPA-36009',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'CCPA signer does not match the expected party',
    description: 'A readable CCPA signer name differs from the expected party name',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  BLOCKER_CCPA_INSUFFICIENT_SIGNATURE_FIELDS: {
    id: 'BLOCKER_CCPA_INSUFFICIENT_SIGNATURE_FIELDS',
    compositeId: 'BLOCKER-CCPA-36010',
    type: 'blocker',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'CCPA does not contain enough signature fields for all expected signers',
    description: 'The CCPA provides two signature lines but more than two signers were expected',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_CCPA_SIGNER_COUNT_UNKNOWN: {
    id: 'WARN_CCPA_SIGNER_COUNT_UNKNOWN',
    compositeId: 'WARN-CCPA-36011',
    type: 'warning',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'Expected CCPA signer count is unknown',
    description: 'Signature completion cannot be confirmed without the expected signer count',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_CCPA_SIGNATURE_UNREADABLE: {
    id: 'WARN_CCPA_SIGNATURE_UNREADABLE',
    compositeId: 'WARN-CCPA-36012',
    type: 'warning',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'A CCPA signature is present but unreadable',
    description: 'The execution mark is present but signer identity requires manual review',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_CCPA_DATE_UNREADABLE: {
    id: 'WARN_CCPA_DATE_UNREADABLE',
    compositeId: 'WARN-CCPA-36013',
    type: 'warning',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'A CCPA signature date is present but unreadable',
    description: 'The date mark requires manual review',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  WARN_CCPA_ROLE_UNKNOWN: {
    id: 'WARN_CCPA_ROLE_UNKNOWN',
    compositeId: 'WARN-CCPA-36014',
    type: 'warning',
    formCode: 'CCPA',
    combinations: ['CCPA:*'],
    message: 'The applicable CCPA party role is unknown',
    description: 'The signer could not be classified as Buyer, Seller, Landlord, or Tenant',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-07-27',
  },

  // ── RR — Request for Repair (40001–40999) ─────────────────────────────────

  WARN_RR_PROPERTY_ADDRESS: {
    id: 'WARN_RR_PROPERTY_ADDRESS',
    compositeId: 'WARN-RR-40001',
    type: 'warning',
    formCode: 'RR',
    combinations: ['RR:*'],
    message: 'Property address not identified on RR (Header, Page 1)',
    description: 'The property address should be clearly indicated on the RR form',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RR_PAGE_MISSING: {
    id: 'BLOCKER_RR_PAGE_MISSING',
    compositeId: 'BLOCKER-RR-40002',
    type: 'blocker',
    formCode: 'RR',
    combinations: ['RR:*'],
    message: 'RR page count could not be identified',
    description: 'Every page footer must show a legible "Page X of Y" for the required-pages check to pass',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RR_MISSING_ITEMS: {
    id: 'BLOCKER_RR_MISSING_ITEMS',
    compositeId: 'BLOCKER-RR-40003',
    type: 'blocker',
    formCode: 'RR',
    combinations: ['RR:*'],
    message: 'RR does not list any requested repair items',
    description: 'A Request for Repair must specify at least one requested repair or credit item',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RR_BUYER_SIG: {
    id: 'BLOCKER_RR_BUYER_SIG',
    compositeId: 'BLOCKER-RR-40004',
    type: 'blocker',
    formCode: 'RR',
    combinations: ['RR:*'],
    message: 'Buyer has not signed the RR',
    description: 'The buyer must sign the RR (Page 1) for the request to be valid',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RR_BUYER_DATE: {
    id: 'BLOCKER_RR_BUYER_DATE',
    compositeId: 'BLOCKER-RR-40005',
    type: 'blocker',
    formCode: 'RR',
    combinations: ['RR:*'],
    message: 'Buyer signature date is missing on the RR',
    description: 'The buyer must date their signature on the RR',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RR_ADDRESS_MISMATCH: {
    id: 'BLOCKER_RR_ADDRESS_MISMATCH',
    compositeId: 'BLOCKER-RR-40006',
    type: 'blocker',
    formCode: 'RR',
    combinations: ['RR:*'],
    message: "RR's property address does not match this transaction's property address",
    description: 'The extracted property address must match the transaction it was uploaded to',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  // ── RRRR — Seller's Response to Buyer's Request for Repair (41001–41999) ──

  WARN_RRRR_PROPERTY_ADDRESS: {
    id: 'WARN_RRRR_PROPERTY_ADDRESS',
    compositeId: 'WARN-RRRR-41001',
    type: 'warning',
    formCode: 'RRRR',
    combinations: ['RRRR:*'],
    message: 'Property address not identified on RRRR (Header, Page 1)',
    description: 'The property address should be clearly indicated on the RRRR form',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RRRR_PAGE_MISSING: {
    id: 'BLOCKER_RRRR_PAGE_MISSING',
    compositeId: 'BLOCKER-RRRR-41002',
    type: 'blocker',
    formCode: 'RRRR',
    combinations: ['RRRR:*'],
    message: 'RRRR page count could not be identified',
    description: 'Every page footer must show a legible "Page X of Y" for the required-pages check to pass',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RRRR_MISSING_ITEMS: {
    id: 'BLOCKER_RRRR_MISSING_ITEMS',
    compositeId: 'BLOCKER-RRRR-41003',
    type: 'blocker',
    formCode: 'RRRR',
    combinations: ['RRRR:*'],
    message: 'RRRR does not list any response items',
    description: "A Seller's Response to Request for Repair must respond to at least one item",
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RRRR_SELLER_SIG: {
    id: 'BLOCKER_RRRR_SELLER_SIG',
    compositeId: 'BLOCKER-RRRR-41004',
    type: 'blocker',
    formCode: 'RRRR',
    combinations: ['RRRR:*'],
    message: 'Seller has not signed the RRRR',
    description: 'The seller must sign the RRRR (Page 1) for the response to be valid',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RRRR_SELLER_DATE: {
    id: 'BLOCKER_RRRR_SELLER_DATE',
    compositeId: 'BLOCKER-RRRR-41005',
    type: 'blocker',
    formCode: 'RRRR',
    combinations: ['RRRR:*'],
    message: 'Seller signature date is missing on the RRRR',
    description: 'The seller must date their signature on the RRRR',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_RRRR_ADDRESS_MISMATCH: {
    id: 'BLOCKER_RRRR_ADDRESS_MISMATCH',
    compositeId: 'BLOCKER-RRRR-41006',
    type: 'blocker',
    formCode: 'RRRR',
    combinations: ['RRRR:*'],
    message: "RRRR's property address does not match this transaction's property address",
    description: 'The extracted property address must match the transaction it was uploaded to',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  // ── CR-B — Contingency Removal (Buyer) (42001–42999) ────────────────────────

  WARN_CRB_PROPERTY_ADDRESS: {
    id: 'WARN_CRB_PROPERTY_ADDRESS',
    compositeId: 'WARN-CRB-42001',
    type: 'warning',
    formCode: 'CR-B',
    combinations: ['CR-B:*'],
    message: 'Property address not identified on CR-B (Header, Page 1)',
    description: 'The property address should be clearly indicated on the CR-B form',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_CRB_PAGE_MISSING: {
    id: 'BLOCKER_CRB_PAGE_MISSING',
    compositeId: 'BLOCKER-CRB-42002',
    type: 'blocker',
    formCode: 'CR-B',
    combinations: ['CR-B:*'],
    message: 'CR-B page count could not be identified',
    description: 'Every page footer must show a legible "Page X of Y" for the required-pages check to pass',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_CRB_NO_CONTINGENCY_SELECTED: {
    id: 'BLOCKER_CRB_NO_CONTINGENCY_SELECTED',
    compositeId: 'BLOCKER-CRB-42003',
    type: 'blocker',
    formCode: 'CR-B',
    combinations: ['CR-B:*'],
    message: 'CR-B does not select any contingency to remove',
    description: 'A Contingency Removal must check at least one of inspection, loan, appraisal, or all contingencies',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_CRB_BUYER_SIG: {
    id: 'BLOCKER_CRB_BUYER_SIG',
    compositeId: 'BLOCKER-CRB-42004',
    type: 'blocker',
    formCode: 'CR-B',
    combinations: ['CR-B:*'],
    message: 'Buyer has not signed the CR-B',
    description: 'The buyer must sign the CR-B (Page 1) for the removal to be valid',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_CRB_BUYER_DATE: {
    id: 'BLOCKER_CRB_BUYER_DATE',
    compositeId: 'BLOCKER-CRB-42005',
    type: 'blocker',
    formCode: 'CR-B',
    combinations: ['CR-B:*'],
    message: 'Buyer signature date is missing on the CR-B',
    description: 'The buyer must date their signature on the CR-B',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_CRB_ADDRESS_MISMATCH: {
    id: 'BLOCKER_CRB_ADDRESS_MISMATCH',
    compositeId: 'BLOCKER-CRB-42006',
    type: 'blocker',
    formCode: 'CR-B',
    combinations: ['CR-B:*'],
    message: "CR-B's property address does not match this transaction's property address",
    description: 'The extracted property address must match the transaction it was uploaded to',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  // ── VP — Verification of Property Condition (43001–43999) ──────────────────

  WARN_VP_PROPERTY_ADDRESS: {
    id: 'WARN_VP_PROPERTY_ADDRESS',
    compositeId: 'WARN-VP-43001',
    type: 'warning',
    formCode: 'VP',
    combinations: ['VP:*'],
    message: 'Property address not identified on VP (Header, Page 1)',
    description: 'The property address should be clearly indicated on the VP form',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_VP_PAGE_MISSING: {
    id: 'BLOCKER_VP_PAGE_MISSING',
    compositeId: 'BLOCKER-VP-43002',
    type: 'blocker',
    formCode: 'VP',
    combinations: ['VP:*'],
    message: 'VP page count could not be identified',
    description: 'Every page footer must show a legible "Page X of Y" for the required-pages check to pass',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_VP_NOT_VERIFIED: {
    id: 'BLOCKER_VP_NOT_VERIFIED',
    compositeId: 'BLOCKER-VP-43003',
    type: 'blocker',
    formCode: 'VP',
    combinations: ['VP:*'],
    message: 'VP does not confirm the property condition has been verified',
    description: 'A Verification of Property must confirm the Buyer has verified the property condition',
    category: 'forms_disclosures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_VP_BUYER_SIG: {
    id: 'BLOCKER_VP_BUYER_SIG',
    compositeId: 'BLOCKER-VP-43004',
    type: 'blocker',
    formCode: 'VP',
    combinations: ['VP:*'],
    message: 'Buyer has not signed the VP',
    description: 'The buyer must sign the VP (Page 1) for the verification to be valid',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_VP_BUYER_DATE: {
    id: 'BLOCKER_VP_BUYER_DATE',
    compositeId: 'BLOCKER-VP-43005',
    type: 'blocker',
    formCode: 'VP',
    combinations: ['VP:*'],
    message: 'Buyer signature date is missing on the VP',
    description: 'The buyer must date their signature on the VP',
    category: 'signatures',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },

  BLOCKER_VP_ADDRESS_MISMATCH: {
    id: 'BLOCKER_VP_ADDRESS_MISMATCH',
    compositeId: 'BLOCKER-VP-43006',
    type: 'blocker',
    formCode: 'VP',
    combinations: ['VP:*'],
    message: "VP's property address does not match this transaction's property address",
    description: 'The extracted property address must match the transaction it was uploaded to',
    category: 'property',
    phase: 'disclosure',
    effective: true,
    introducedBy: 'system',
    dateAdded: '2026-08-04',
  },
};

/** Resolve a disclosures-stage blocker code to its output shape. `message` overrides the catalog's static text when the issue needs to say something specific (e.g. which item number is involved). */
export function resolveDisclosuresBlocker(
  code: string,
  fields?: string[],
  location?: string,
  message?: string,
): { code: string; compositeId: string; message: string; formCode: string; type: 'blocker'; fields?: string[]; location?: string } | null {
  const entry = DISCLOSURES_BLOCKER_CATALOG[code];
  if (!entry || !entry.effective || entry.type !== 'blocker') return null;
  return { code: entry.id, compositeId: entry.compositeId, message: message ?? entry.message, formCode: entry.formCode, type: 'blocker', fields, location };
}

/** Resolve a disclosures-stage warning code to its output shape. `message` overrides the catalog's static text when the issue needs to say something specific. */
export function resolveDisclosuresWarning(
  code: string,
  fields?: string[],
  location?: string,
  message?: string,
): { code: string; compositeId: string; message: string; formCode: string; type: 'warning'; fields?: string[]; location?: string } | null {
  const entry = DISCLOSURES_BLOCKER_CATALOG[code];
  if (!entry || !entry.effective || entry.type !== 'warning') return null;
  return { code: entry.id, compositeId: entry.compositeId, message: message ?? entry.message, formCode: entry.formCode, type: 'warning', fields, location };
}
