import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserRolesArray1779947878846 implements MigrationInterface {
    name = 'AddUserRolesArray1779947878846'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transaction_form_template_items" DROP CONSTRAINT "FK_form_item_template"`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" DROP CONSTRAINT "FK_form_template_created_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" DROP CONSTRAINT "FK_form_template_org"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_party_delegated_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_party_account"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_party_org"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_party_contact"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_party_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" DROP CONSTRAINT "FK_wf_template_created_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" DROP CONSTRAINT "FK_wf_template_org"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_template_steps" DROP CONSTRAINT "FK_wf_template_step_template"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" DROP CONSTRAINT "FK_wf_step_template_step"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" DROP CONSTRAINT "FK_wf_step_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_task_workflow_step"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_task_created_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_task_depends_on"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_task_assigned"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_task_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_events" DROP CONSTRAINT "FK_event_created_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_events" DROP CONSTRAINT "FK_event_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" DROP CONSTRAINT "FK_journal_actor"`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" DROP CONSTRAINT "FK_journal_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_message_workflow_step"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_message_recipient"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_message_sender"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_message_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" DROP CONSTRAINT "FK_tds_submitted_by_party"`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" DROP CONSTRAINT "FK_tds_transaction"`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" DROP CONSTRAINT "FK_ai_actor"`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" DROP CONSTRAINT "FK_ai_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_td_ai_interaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_td_previous_version"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_td_submission"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_doc_workflow_step"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_doc_uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_doc_requested_from"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_doc_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" DROP CONSTRAINT "FK_transaction_stage_instances_account"`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" DROP CONSTRAINT "FK_transaction_stage_instances_transaction"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "fk_transaction_form_template"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "FK_transaction_coordinator"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "FK_transaction_created_by"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "FK_transaction_org"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "FK_membership_account"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "FK_membership_org"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_accounts_user"`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" DROP CONSTRAINT "FK_invitation_accepted_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" DROP CONSTRAINT "FK_invitation_invited_by"`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" DROP CONSTRAINT "FK_invitation_transaction"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP CONSTRAINT "transaction_access_grants_granted_by_account_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP CONSTRAINT "transaction_access_grants_account_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP CONSTRAINT "transaction_access_grants_transaction_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "fk_audit_logs_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USERS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."idx_form_template_items_stage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FORM_ITEMS_TEMPLATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FORM_ITEMS_ORDER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FORM_TMPL_ORG"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FORM_TMPL_STATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_FORM_TMPL_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CONTACTS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_CONTACTS_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PARTIES_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PARTIES_ROLE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PARTIES_ACCOUNT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PARTIES_DELEGATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_TEMPLATES_STATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_TEMPLATES_ORG"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_TEMPLATES_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_TMPL_STEPS_TEMPLATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_TMPL_STEPS_ORDER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_STEPS_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_STEPS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WF_STEPS_ORDER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_WF_STEP"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_ASSIGNED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_DUE_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EVENTS_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EVENTS_EVENT_DATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_EVENTS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_JOURNALS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_JOURNALS_TX_DATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_CHANNEL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_THREAD_KEY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_PROVIDER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_WF_STEP"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_messages_stage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MESSAGES_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tds_transaction_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_tds_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_ACCOUNT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_FEATURE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_AI_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCS_DUE_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_td_submission_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_td_previous_version_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_td_ai_interaction_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_documents_transaction_stage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCS_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_DOCS_WF_STEP"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stage_instances_transactionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stage_instances_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_real_estate_transactions_form_template_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TX_ORG_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TX_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TX_CLOSE_DATE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORGS_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ORGS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MEMBERSHIPS_ACCOUNT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_MEMBERSHIPS_ROLE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ACCOUNTS_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVITATIONS_TX"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVITATIONS_EMAIL"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVITATIONS_TOKEN"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_access_grants_transaction_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_transaction_access_grants_account_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_account_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_action_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_target"`);
        await queryRunner.query(`ALTER TABLE "transaction_form_template_items" DROP CONSTRAINT "UQ_form_item_template_code"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_template_steps" DROP CONSTRAINT "UQ_wf_template_step_key"`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" DROP CONSTRAINT "UQ_tds_transaction_submission_no"`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" DROP CONSTRAINT "UQ_transaction_stage_instances_tx_stage"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "UQ_org_member"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP CONSTRAINT "uq_transaction_access_grants_tx_account"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "transaction_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "account_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "granted_by_account_id"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "access_level"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "granted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "revoked_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "roles" text array NOT NULL DEFAULT '{user}'`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "transactionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "accountId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "grantedByAccountId" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "accessLevel" character varying NOT NULL DEFAULT 'collaborate'`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "grantedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "expiresAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "revokedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`COMMENT ON COLUMN "real_estate_transactions"."outbound_email_address" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_156eb3fad6881f3aa97e6a1728" ON "transaction_form_template_items" ("templateId", "sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_20ee86f2bee6a49e074e7897b7" ON "transaction_form_template_items" ("templateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_300db0d0d0293f18133e679ed8" ON "transaction_form_templates" ("transactionType", "side") `);
        await queryRunner.query(`CREATE INDEX "IDX_773a747072c608adc3c49cb83d" ON "transaction_form_templates" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ad5ef49b1a730532d3ae2fe83" ON "transaction_form_templates" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d5994fa4823da717519d3b4e1" ON "transaction_parties" ("partyRole") `);
        await queryRunner.query(`CREATE INDEX "IDX_31f2f48ae910f8396c17200c02" ON "transaction_parties" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_54603ce1dde53336303451013e" ON "transaction_workflow_templates" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_39b4d811c86482045026808b65" ON "transaction_workflow_templates" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7128322b3cd4e977ccfad224a0" ON "transaction_workflow_template_steps" ("templateId", "sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d67ee29bbfbd84064ff1fa236" ON "transaction_workflow_template_steps" ("templateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c16d6f14d233d9ead5c389ca5" ON "transaction_workflow_steps" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_18c73802ef02ba34373cc85606" ON "transaction_workflow_steps" ("transactionId", "sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7891853b371ed31f958ca2c81" ON "transaction_workflow_steps" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb03fea04253c66a8f4a19dbec" ON "transaction_tasks" ("dueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_92591a31c320d52f31cfefaf05" ON "transaction_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_611ec5e6babed820d632546352" ON "transaction_tasks" ("assignedAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9112111c89068a692ac622485c" ON "transaction_tasks" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8caa5c5ceb4060a8a0e50ce2f5" ON "transaction_events" ("eventDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f7f6d0b1f927a1808025877da" ON "transaction_events" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb36c4540e02d553aea476fd30" ON "transaction_journals" ("journalType") `);
        await queryRunner.query(`CREATE INDEX "IDX_49af83ef54950c421598751f00" ON "transaction_journals" ("transactionId", "eventAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3cd12186cfc2494557d3ac9aa" ON "transaction_messages" ("threadKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0b4b5cb14073eb24007241e91" ON "transaction_messages" ("channel") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b3a73130b7a13fa960fc678ea" ON "transaction_messages" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3778d2a054f83b6af483022e6b" ON "transaction_document_submissions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_95d634aff22b2775de757bce0c" ON "transaction_document_submissions" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1e4bc5bc10e268b2f014b5945" ON "ai_interactions" ("actorAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9d640c3000bc5f8654ca3856f" ON "ai_interactions" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0b93ae86e528f6c1a9d61069d" ON "transaction_documents" ("dueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_258016c2f17f64699f70b8eeb3" ON "transaction_documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9049c3dc6abbcac49a3b9f05e5" ON "transaction_documents" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d1a1db98c097a9e7ff7bc14cc" ON "transaction_stage_instances" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_21660c93e241fb73dfd8c93ebc" ON "transaction_stage_instances" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bba2092507c50bee71cb179e2c" ON "real_estate_transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad33e4293265db9a0a8ef27dbd" ON "real_estate_transactions" ("organizationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7c543bdedf46c9828590e0e13" ON "organization_memberships" ("organizationId", "accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4628b495632b4062a3cd44e122" ON "transaction_party_invitations" ("invitedEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_815f716e928a7458653ffacb0f" ON "transaction_party_invitations" ("transactionId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7df657f936317fab682377e6e8" ON "transaction_access_grants" ("transactionId", "accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f39b7c60bef405b6ac5bfd6192" ON "transaction_access_grants" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f35e67f72ab0df64cfd96ed87" ON "transaction_access_grants" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61614f246ac701597f688946b9" ON "audit_logs" ("targetType", "targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ec936941eb8556fcd7a1f0eae" ON "audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d19519a7ff4bd3bd15bac04f9e" ON "audit_logs" ("accountId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" ADD CONSTRAINT "UQ_c705d85ee3db09bd4547939a748" UNIQUE ("transactionId", "stage")`);
        await queryRunner.query(`ALTER TABLE "transaction_form_template_items" ADD CONSTRAINT "FK_20ee86f2bee6a49e074e7897b7a" FOREIGN KEY ("templateId") REFERENCES "transaction_form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" ADD CONSTRAINT "FK_5ad5ef49b1a730532d3ae2fe83f" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" ADD CONSTRAINT "FK_5721d05f376c7d599edb5ebcad2" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_31f2f48ae910f8396c17200c023" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_f080384314f03beab31741c6688" FOREIGN KEY ("contactId") REFERENCES "contacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_7a13b7eda038058286fa7e24065" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_452eeed48bc96fd1c438bf6fe57" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_adb36fe2c0c2026964f9ddc6724" FOREIGN KEY ("delegatedByPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" ADD CONSTRAINT "FK_39b4d811c86482045026808b65e" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" ADD CONSTRAINT "FK_006174035bf5f2b23cf45853556" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_template_steps" ADD CONSTRAINT "FK_5d67ee29bbfbd84064ff1fa2366" FOREIGN KEY ("templateId") REFERENCES "transaction_workflow_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" ADD CONSTRAINT "FK_f7891853b371ed31f958ca2c81d" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" ADD CONSTRAINT "FK_00ac26010f781d4444dae566fc7" FOREIGN KEY ("templateStepId") REFERENCES "transaction_workflow_template_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_9112111c89068a692ac622485cb" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_611ec5e6babed820d632546352d" FOREIGN KEY ("assignedAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_8d1983d689551b98a8321f2bbe2" FOREIGN KEY ("dependsOnTaskId") REFERENCES "transaction_tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_3c2c03f57658f603f21c9266f98" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_e16c7b121c54e774fe437435cd4" FOREIGN KEY ("workflowStepId") REFERENCES "transaction_workflow_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_events" ADD CONSTRAINT "FK_9f7f6d0b1f927a1808025877da6" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_events" ADD CONSTRAINT "FK_a33a9ae7cce3bcef67b908caa2e" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" ADD CONSTRAINT "FK_92908a51c225c1ad4dbbdd30b2c" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" ADD CONSTRAINT "FK_e06d4575f1dbaa975c620f7fdf3" FOREIGN KEY ("actorAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_0b3a73130b7a13fa960fc678eae" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_d627e3385add7d8d0ad34fba39f" FOREIGN KEY ("senderPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_eb5b8e8ffdca3d3d0da97876a18" FOREIGN KEY ("recipientPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_746d3735a0a97d8f28cd5b71cae" FOREIGN KEY ("workflowStepId") REFERENCES "transaction_workflow_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" ADD CONSTRAINT "FK_95d634aff22b2775de757bce0c3" FOREIGN KEY ("transaction_id") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" ADD CONSTRAINT "FK_6e811a9d9ab5b3ec9b7c5fad848" FOREIGN KEY ("submitted_by_party_id") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" ADD CONSTRAINT "FK_a9d640c3000bc5f8654ca3856f0" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" ADD CONSTRAINT "FK_c1e4bc5bc10e268b2f014b59453" FOREIGN KEY ("actorAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_9049c3dc6abbcac49a3b9f05e51" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_fba33c5d0873adbf2e8c897230e" FOREIGN KEY ("requestedFromPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_85c76b118b27767b83344ea5c4d" FOREIGN KEY ("uploadedByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_6939362422f63d23ece2533d74a" FOREIGN KEY ("workflowStepId") REFERENCES "transaction_workflow_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_ca317480f25d3b1e2045bad03cb" FOREIGN KEY ("submission_id") REFERENCES "transaction_document_submissions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_65548a9f77f4470a90a4c8bf660" FOREIGN KEY ("ai_interaction_id") REFERENCES "ai_interactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_2c78648e4f684f42ac8dc4ebf68" FOREIGN KEY ("previous_version_id") REFERENCES "transaction_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" ADD CONSTRAINT "FK_21660c93e241fb73dfd8c93ebc4" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" ADD CONSTRAINT "FK_9b04200645c02eec0b53c5cf2e2" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "FK_ad33e4293265db9a0a8ef27dbd5" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "FK_24592e7c15ca175e173c6b1a665" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "FK_3f6233bd20ba638af2965d4cba5" FOREIGN KEY ("assignedCoordinatorAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "FK_79141d051c330ac3538486b1d11" FOREIGN KEY ("form_template_id") REFERENCES "transaction_form_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "FK_1813e7f46b5a18529482f519640" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "FK_a40324fd22d6e90a764d301233d" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" ADD CONSTRAINT "FK_815f716e928a7458653ffacb0f0" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" ADD CONSTRAINT "FK_2a0aa3c80b53758da10e5f0e95f" FOREIGN KEY ("invitedByAccountId") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" ADD CONSTRAINT "FK_ccf383369d6f374576b8c1a87c1" FOREIGN KEY ("acceptedByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD CONSTRAINT "FK_2f35e67f72ab0df64cfd96ed875" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD CONSTRAINT "FK_f39b7c60bef405b6ac5bfd6192c" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD CONSTRAINT "FK_e3f7bfa989928c5d7c9c6472a97" FOREIGN KEY ("grantedByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_2379f36450fb7644e4d059a85d2" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_2379f36450fb7644e4d059a85d2"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP CONSTRAINT "FK_e3f7bfa989928c5d7c9c6472a97"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP CONSTRAINT "FK_f39b7c60bef405b6ac5bfd6192c"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP CONSTRAINT "FK_2f35e67f72ab0df64cfd96ed875"`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" DROP CONSTRAINT "FK_ccf383369d6f374576b8c1a87c1"`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" DROP CONSTRAINT "FK_2a0aa3c80b53758da10e5f0e95f"`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" DROP CONSTRAINT "FK_815f716e928a7458653ffacb0f0"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "FK_a40324fd22d6e90a764d301233d"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "FK_1813e7f46b5a18529482f519640"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "FK_79141d051c330ac3538486b1d11"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "FK_3f6233bd20ba638af2965d4cba5"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "FK_24592e7c15ca175e173c6b1a665"`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" DROP CONSTRAINT "FK_ad33e4293265db9a0a8ef27dbd5"`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" DROP CONSTRAINT "FK_9b04200645c02eec0b53c5cf2e2"`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" DROP CONSTRAINT "FK_21660c93e241fb73dfd8c93ebc4"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_2c78648e4f684f42ac8dc4ebf68"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_65548a9f77f4470a90a4c8bf660"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_ca317480f25d3b1e2045bad03cb"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_6939362422f63d23ece2533d74a"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_85c76b118b27767b83344ea5c4d"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_fba33c5d0873adbf2e8c897230e"`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" DROP CONSTRAINT "FK_9049c3dc6abbcac49a3b9f05e51"`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" DROP CONSTRAINT "FK_c1e4bc5bc10e268b2f014b59453"`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" DROP CONSTRAINT "FK_a9d640c3000bc5f8654ca3856f0"`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" DROP CONSTRAINT "FK_6e811a9d9ab5b3ec9b7c5fad848"`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" DROP CONSTRAINT "FK_95d634aff22b2775de757bce0c3"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_746d3735a0a97d8f28cd5b71cae"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_eb5b8e8ffdca3d3d0da97876a18"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_d627e3385add7d8d0ad34fba39f"`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" DROP CONSTRAINT "FK_0b3a73130b7a13fa960fc678eae"`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" DROP CONSTRAINT "FK_e06d4575f1dbaa975c620f7fdf3"`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" DROP CONSTRAINT "FK_92908a51c225c1ad4dbbdd30b2c"`);
        await queryRunner.query(`ALTER TABLE "transaction_events" DROP CONSTRAINT "FK_a33a9ae7cce3bcef67b908caa2e"`);
        await queryRunner.query(`ALTER TABLE "transaction_events" DROP CONSTRAINT "FK_9f7f6d0b1f927a1808025877da6"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_e16c7b121c54e774fe437435cd4"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_3c2c03f57658f603f21c9266f98"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_8d1983d689551b98a8321f2bbe2"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_611ec5e6babed820d632546352d"`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" DROP CONSTRAINT "FK_9112111c89068a692ac622485cb"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" DROP CONSTRAINT "FK_00ac26010f781d4444dae566fc7"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" DROP CONSTRAINT "FK_f7891853b371ed31f958ca2c81d"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_template_steps" DROP CONSTRAINT "FK_5d67ee29bbfbd84064ff1fa2366"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" DROP CONSTRAINT "FK_006174035bf5f2b23cf45853556"`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" DROP CONSTRAINT "FK_39b4d811c86482045026808b65e"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_adb36fe2c0c2026964f9ddc6724"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_452eeed48bc96fd1c438bf6fe57"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_7a13b7eda038058286fa7e24065"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_f080384314f03beab31741c6688"`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" DROP CONSTRAINT "FK_31f2f48ae910f8396c17200c023"`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" DROP CONSTRAINT "FK_5721d05f376c7d599edb5ebcad2"`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" DROP CONSTRAINT "FK_5ad5ef49b1a730532d3ae2fe83f"`);
        await queryRunner.query(`ALTER TABLE "transaction_form_template_items" DROP CONSTRAINT "FK_20ee86f2bee6a49e074e7897b7a"`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" DROP CONSTRAINT "UQ_c705d85ee3db09bd4547939a748"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d19519a7ff4bd3bd15bac04f9e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ec936941eb8556fcd7a1f0eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61614f246ac701597f688946b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f35e67f72ab0df64cfd96ed87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f39b7c60bef405b6ac5bfd6192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7df657f936317fab682377e6e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_815f716e928a7458653ffacb0f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4628b495632b4062a3cd44e122"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7c543bdedf46c9828590e0e13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad33e4293265db9a0a8ef27dbd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bba2092507c50bee71cb179e2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21660c93e241fb73dfd8c93ebc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d1a1db98c097a9e7ff7bc14cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9049c3dc6abbcac49a3b9f05e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_258016c2f17f64699f70b8eeb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0b93ae86e528f6c1a9d61069d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9d640c3000bc5f8654ca3856f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1e4bc5bc10e268b2f014b5945"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95d634aff22b2775de757bce0c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3778d2a054f83b6af483022e6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b3a73130b7a13fa960fc678ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0b4b5cb14073eb24007241e91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3cd12186cfc2494557d3ac9aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49af83ef54950c421598751f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb36c4540e02d553aea476fd30"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f7f6d0b1f927a1808025877da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8caa5c5ceb4060a8a0e50ce2f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9112111c89068a692ac622485c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_611ec5e6babed820d632546352"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92591a31c320d52f31cfefaf05"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb03fea04253c66a8f4a19dbec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7891853b371ed31f958ca2c81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18c73802ef02ba34373cc85606"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c16d6f14d233d9ead5c389ca5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d67ee29bbfbd84064ff1fa236"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7128322b3cd4e977ccfad224a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39b4d811c86482045026808b65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54603ce1dde53336303451013e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31f2f48ae910f8396c17200c02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d5994fa4823da717519d3b4e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ad5ef49b1a730532d3ae2fe83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_773a747072c608adc3c49cb83d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_300db0d0d0293f18133e679ed8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20ee86f2bee6a49e074e7897b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156eb3fad6881f3aa97e6a1728"`);
        await queryRunner.query(`COMMENT ON COLUMN "real_estate_transactions"."outbound_email_address" IS 'The From address used for all outbound emails on this transaction.
         Format: {8-char-org-prefix}-{sanitized-street}-{zip}@txn.mytcapp.net
         Computed once at transaction creation from organizationId + propertyAddressLine1
         + propertyPostalCode and never mutated, so Mailgun routing rules and inbound
         reply matching always resolve back to the correct transaction row.
         NULL when the property address was not available at creation time.'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "revokedAt"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "grantedAt"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "accessLevel"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "grantedByAccountId"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "roles"`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "revoked_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "expires_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "granted_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "access_level" character varying NOT NULL DEFAULT 'collaborate'`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "granted_by_account_id" uuid`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "account_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD "transaction_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD CONSTRAINT "uq_transaction_access_grants_tx_account" UNIQUE ("transaction_id", "account_id")`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "UQ_org_member" UNIQUE ("organizationId", "accountId")`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" ADD CONSTRAINT "UQ_transaction_stage_instances_tx_stage" UNIQUE ("transactionId", "stage")`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" ADD CONSTRAINT "UQ_tds_transaction_submission_no" UNIQUE ("transaction_id", "submission_no")`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_template_steps" ADD CONSTRAINT "UQ_wf_template_step_key" UNIQUE ("templateId", "stepKey")`);
        await queryRunner.query(`ALTER TABLE "transaction_form_template_items" ADD CONSTRAINT "UQ_form_item_template_code" UNIQUE ("templateId", "formCode")`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_target" ON "audit_logs" ("targetType", "targetId") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action_created" ON "audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_account_created" ON "audit_logs" ("accountId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_access_grants_account_id" ON "transaction_access_grants" ("account_id") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_access_grants_transaction_id" ON "transaction_access_grants" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_INVITATIONS_TOKEN" ON "transaction_party_invitations" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_INVITATIONS_EMAIL" ON "transaction_party_invitations" ("invitedEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_INVITATIONS_TX" ON "transaction_party_invitations" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ACCOUNTS_STATUS" ON "accounts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_MEMBERSHIPS_ROLE" ON "organization_memberships" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_MEMBERSHIPS_ACCOUNT" ON "organization_memberships" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORGS_STATUS" ON "real_estate_organizations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ORGS_TYPE" ON "real_estate_organizations" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_TX_CLOSE_DATE" ON "real_estate_transactions" ("closeOfEscrowAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_TX_STATUS" ON "real_estate_transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_TX_ORG_ID" ON "real_estate_transactions" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "idx_real_estate_transactions_form_template_id" ON "real_estate_transactions" ("form_template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_stage_instances_status" ON "transaction_stage_instances" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_stage_instances_transactionId" ON "transaction_stage_instances" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCS_WF_STEP" ON "transaction_documents" ("workflowStepId") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCS_TX" ON "transaction_documents" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_documents_transaction_stage" ON "transaction_documents" ("transactionId", "stage") WHERE (stage IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_DOCS_STATUS" ON "transaction_documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_td_ai_interaction_id" ON "transaction_documents" ("ai_interaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_td_previous_version_id" ON "transaction_documents" ("previous_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_td_submission_id" ON "transaction_documents" ("submission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCS_DUE_AT" ON "transaction_documents" ("dueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_TX" ON "ai_interactions" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_FEATURE" ON "ai_interactions" ("feature") `);
        await queryRunner.query(`CREATE INDEX "IDX_AI_ACCOUNT" ON "ai_interactions" ("actorAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_tds_status" ON "transaction_document_submissions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_tds_transaction_id" ON "transaction_document_submissions" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_TX" ON "transaction_messages" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "idx_transaction_messages_stage" ON "transaction_messages" ("transactionId", "stage") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_WF_STEP" ON "transaction_messages" ("workflowStepId") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_PROVIDER_ID" ON "transaction_messages" ("providerMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_THREAD_KEY" ON "transaction_messages" ("threadKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_MESSAGES_CHANNEL" ON "transaction_messages" ("channel") `);
        await queryRunner.query(`CREATE INDEX "IDX_JOURNALS_TX_DATE" ON "transaction_journals" ("transactionId", "eventAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_JOURNALS_TYPE" ON "transaction_journals" ("journalType") `);
        await queryRunner.query(`CREATE INDEX "IDX_EVENTS_TYPE" ON "transaction_events" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_EVENTS_EVENT_DATE" ON "transaction_events" ("eventDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_EVENTS_TX" ON "transaction_events" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_DUE_AT" ON "transaction_tasks" ("dueAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_STATUS" ON "transaction_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_ASSIGNED" ON "transaction_tasks" ("assignedAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_TX" ON "transaction_tasks" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_WF_STEP" ON "transaction_tasks" ("workflowStepId") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_STEPS_ORDER" ON "transaction_workflow_steps" ("transactionId", "sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_STEPS_STATUS" ON "transaction_workflow_steps" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_STEPS_TX" ON "transaction_workflow_steps" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_TMPL_STEPS_ORDER" ON "transaction_workflow_template_steps" ("templateId", "sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_TMPL_STEPS_TEMPLATE" ON "transaction_workflow_template_steps" ("templateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_TEMPLATES_TYPE" ON "transaction_workflow_templates" ("transactionType", "side") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_TEMPLATES_ORG" ON "transaction_workflow_templates" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_WF_TEMPLATES_STATE" ON "transaction_workflow_templates" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_PARTIES_DELEGATED" ON "transaction_parties" ("delegatedByPartyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_PARTIES_ACCOUNT" ON "transaction_parties" ("accountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_PARTIES_ROLE" ON "transaction_parties" ("partyRole") `);
        await queryRunner.query(`CREATE INDEX "IDX_PARTIES_TX" ON "transaction_parties" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_CONTACTS_EMAIL" ON "contacts" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_CONTACTS_TYPE" ON "contacts" ("contactType") `);
        await queryRunner.query(`CREATE INDEX "IDX_FORM_TMPL_TYPE" ON "transaction_form_templates" ("transactionType", "side") `);
        await queryRunner.query(`CREATE INDEX "IDX_FORM_TMPL_STATE" ON "transaction_form_templates" ("stateCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_FORM_TMPL_ORG" ON "transaction_form_templates" ("organizationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_FORM_ITEMS_ORDER" ON "transaction_form_template_items" ("templateId", "sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_FORM_ITEMS_TEMPLATE" ON "transaction_form_template_items" ("templateId") `);
        await queryRunner.query(`CREATE INDEX "idx_form_template_items_stage" ON "transaction_form_template_items" ("templateId", "stage") `);
        await queryRunner.query(`CREATE INDEX "IDX_USERS_STATUS" ON "users" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_USERS_EMAIL" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_account" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD CONSTRAINT "transaction_access_grants_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD CONSTRAINT "transaction_access_grants_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_access_grants" ADD CONSTRAINT "transaction_access_grants_granted_by_account_id_fkey" FOREIGN KEY ("granted_by_account_id") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" ADD CONSTRAINT "FK_invitation_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" ADD CONSTRAINT "FK_invitation_invited_by" FOREIGN KEY ("invitedByAccountId") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_party_invitations" ADD CONSTRAINT "FK_invitation_accepted_by" FOREIGN KEY ("acceptedByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_accounts_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "FK_membership_org" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "FK_membership_account" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "FK_transaction_org" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "FK_transaction_created_by" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "FK_transaction_coordinator" FOREIGN KEY ("assignedCoordinatorAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "real_estate_transactions" ADD CONSTRAINT "fk_transaction_form_template" FOREIGN KEY ("form_template_id") REFERENCES "transaction_form_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" ADD CONSTRAINT "FK_transaction_stage_instances_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_stage_instances" ADD CONSTRAINT "FK_transaction_stage_instances_account" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_doc_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_doc_requested_from" FOREIGN KEY ("requestedFromPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_doc_uploaded_by" FOREIGN KEY ("uploadedByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_doc_workflow_step" FOREIGN KEY ("workflowStepId") REFERENCES "transaction_workflow_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_td_submission" FOREIGN KEY ("submission_id") REFERENCES "transaction_document_submissions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_td_previous_version" FOREIGN KEY ("previous_version_id") REFERENCES "transaction_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_documents" ADD CONSTRAINT "FK_td_ai_interaction" FOREIGN KEY ("ai_interaction_id") REFERENCES "ai_interactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" ADD CONSTRAINT "FK_ai_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_interactions" ADD CONSTRAINT "FK_ai_actor" FOREIGN KEY ("actorAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" ADD CONSTRAINT "FK_tds_transaction" FOREIGN KEY ("transaction_id") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_document_submissions" ADD CONSTRAINT "FK_tds_submitted_by_party" FOREIGN KEY ("submitted_by_party_id") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_message_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_message_sender" FOREIGN KEY ("senderPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_message_recipient" FOREIGN KEY ("recipientPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_messages" ADD CONSTRAINT "FK_message_workflow_step" FOREIGN KEY ("workflowStepId") REFERENCES "transaction_workflow_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" ADD CONSTRAINT "FK_journal_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_journals" ADD CONSTRAINT "FK_journal_actor" FOREIGN KEY ("actorAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_events" ADD CONSTRAINT "FK_event_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_events" ADD CONSTRAINT "FK_event_created_by" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_task_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_task_assigned" FOREIGN KEY ("assignedAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_task_depends_on" FOREIGN KEY ("dependsOnTaskId") REFERENCES "transaction_tasks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_task_created_by" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_tasks" ADD CONSTRAINT "FK_task_workflow_step" FOREIGN KEY ("workflowStepId") REFERENCES "transaction_workflow_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" ADD CONSTRAINT "FK_wf_step_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_steps" ADD CONSTRAINT "FK_wf_step_template_step" FOREIGN KEY ("templateStepId") REFERENCES "transaction_workflow_template_steps"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_template_steps" ADD CONSTRAINT "FK_wf_template_step_template" FOREIGN KEY ("templateId") REFERENCES "transaction_workflow_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" ADD CONSTRAINT "FK_wf_template_org" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_workflow_templates" ADD CONSTRAINT "FK_wf_template_created_by" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_party_transaction" FOREIGN KEY ("transactionId") REFERENCES "real_estate_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_party_contact" FOREIGN KEY ("contactId") REFERENCES "contacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_party_org" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_party_account" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_parties" ADD CONSTRAINT "FK_party_delegated_by" FOREIGN KEY ("delegatedByPartyId") REFERENCES "transaction_parties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" ADD CONSTRAINT "FK_form_template_org" FOREIGN KEY ("organizationId") REFERENCES "real_estate_organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_form_templates" ADD CONSTRAINT "FK_form_template_created_by" FOREIGN KEY ("createdByAccountId") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction_form_template_items" ADD CONSTRAINT "FK_form_item_template" FOREIGN KEY ("templateId") REFERENCES "transaction_form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
