import { FORM_FOOTER_FIELDS, FORM_FOOTER_INSTRUCTION } from '../form-definition';
import type { FormDefinition } from '../form-definition';

const TDS_TEMPLATE = {
  header: {
    ...FORM_FOOTER_FIELDS,
    is_multi_unit: '<boolean>',
    tds_for_all_units: '<boolean>',
    tds_for_only_units: '<string | null>',
    city: '<string | null>',
    county: '<string | null>',
    property_address: '<string | null>',
    date_top_right: '<date: YYYY-MM-DD | null>',
  },
  section_I_substituted_disclosures: {
    inspection_reports_pursuant_to_contract: '<boolean>',
    additional_inspection_reports: '<boolean>',
    additional_reports_description: '<string | null>',
    no_substituted_disclosures: '<boolean>',
  },
  section_II_sellers_information: {
    occupancy: "<'is occupying' | 'is not occupying' | null>",
    A_property_items: {
      range: '<boolean>',
      oven: '<boolean>',
      microwave: '<boolean>',
      dishwasher: '<boolean>',
      trash_compactor: '<boolean>',
      garbage_disposal: '<boolean>',
      washer_dryer_hookups: '<boolean>',
      rain_gutters: '<boolean>',
      burglar_alarms: '<boolean>',
      carbon_monoxide_devices: '<boolean>',
      smoke_detectors: '<boolean>',
      fire_alarm: '<boolean>',
      tv_antenna: '<boolean>',
      satellite_dish: '<boolean>',
      intercom: '<boolean>',
      central_heating: '<boolean>',
      central_air_conditioning: '<boolean>',
      evaporator_cooler: '<boolean>',
      wall_window_air_conditioning: '<boolean>',
      sprinklers: '<boolean>',
      public_sewer_system: '<boolean>',
      septic_tank: '<boolean>',
      sump_pump: '<boolean>',
      water_softener: '<boolean>',
      patio_decking: '<boolean>',
      built_in_barbecue: '<boolean>',
      gazebo: '<boolean>',
      security_gate: '<boolean>',
      garage_attached: '<boolean>',
      garage_not_attached: '<boolean>',
      carport: '<boolean>',
      automatic_garage_door_opener: '<boolean>',
      number_remote_controls: '<string | null>',
      sauna: '<boolean>',
      hot_tub_spa: '<boolean>',
      locking_safety_cover: '<boolean>',
      pool: '<boolean>',
      pool_child_resistant_barrier: '<boolean>',
      pool_spa_heater_gas: '<boolean>',
      pool_spa_heater_solar: '<boolean>',
      pool_spa_heater_electric: '<boolean>',
      water_heater_gas: '<boolean>',
      water_heater_solar: '<boolean>',
      water_heater_electric: '<boolean>',
      water_supply_city: '<boolean>',
      water_supply_well: '<boolean>',
      water_supply_private_utility_other: '<boolean>',
      gas_supply_utility: '<boolean>',
      gas_supply_bottled: '<boolean>',
      window_screens: '<boolean>',
      window_security_bars: '<boolean>',
      quick_release_mechanism_bedroom_windows: '<boolean>',
      water_conserving_plumbing_fixtures: '<boolean>',
      exhaust_fans_in: '<string | null>',
      wiring_220_volt_in: '<string | null>',
      fireplaces_in: '<string | null>',
      gas_starter: '<string | null>',
      roof_type: '<string | null>',
      roof_age: '<string | null>',
      other: '<string | null>',
      items_not_operating: '<boolean>',
      items_not_operating_description: '<string | null>',
    },
    B_defects_malfunctions: {
      aware_of_defects: '<boolean>',
      interior_walls: '<boolean>',
      ceilings: '<boolean>',
      floors: '<boolean>',
      exterior_walls: '<boolean>',
      insulation: '<boolean>',
      roofs: '<boolean>',
      windows: '<boolean>',
      doors: '<boolean>',
      foundation: '<boolean>',
      slabs: '<boolean>',
      driveways: '<boolean>',
      sidewalks: '<boolean>',
      walls_fences: '<boolean>',
      electrical_systems: '<boolean>',
      plumbing_sewers_septics: '<boolean>',
      other_structural_components: '<boolean>',
      describe_defects: '<string | null>',
      explanation: '<string | null>',
    },
    C_environmental_and_legal: {
      '1_environmental_hazards': '<boolean>',
      '2_shared_features': '<boolean>',
      '3_encroachments_easements': '<boolean>',
      '4_room_additions_without_permits': '<boolean>',
      '5_room_additions_not_to_code': '<boolean>',
      '6_fill_compacted_otherwise': '<boolean>',
      '7_settling_slippage_soil_problems': '<boolean>',
      '8_flooding_drainage_grading': '<boolean>',
      '9_major_damage_from_disaster': '<boolean>',
      '10_zoning_violations_setbacks': '<boolean>',
      '11_neighborhood_noise_nuisances': '<boolean>',
      '12_ccrs_deed_restrictions': '<boolean>',
      '13_hoa_authority': '<boolean>',
      '14_common_areas': '<boolean>',
      '15_notices_of_abatement_citations': '<boolean>',
      '16_lawsuits_affecting_property': '<boolean>',
      explanation: '<string | null>',
    },
  },
  section_III_agents_inspection_disclosure_listing: {
    see_attached_avid: '<boolean>',
    agent_notes_no_items: '<boolean>',
    agent_notes_following_items: '<boolean>',
    items_description: '<string | null>',
    agent_broker_name: '<string | null>',
    date: '<date: YYYY-MM-DD | null>',
  },
  section_IV_agents_inspection_disclosure_selling: {
    see_attached_avid: '<boolean>',
    agent_notes_no_items: '<boolean>',
    agent_notes_following_items: '<boolean>',
    items_description: '<string | null>',
    agent_broker_name: '<string | null>',
    date: '<date: YYYY-MM-DD | null>',
  },
  signatures: {
    seller_signature_page_2: '<boolean>',
    seller_signature_page_2_date: '<date: YYYY-MM-DD | null>',
    seller_signature_page_3: '<boolean>',
    seller_signature_page_3_date: '<date: YYYY-MM-DD | null>',
    buyer_signature: '<boolean>',
    buyer_signature_date: '<date: YYYY-MM-DD | null>',
  },
  extractionWarnings: ['<string>'],
};

export const tdsStandardV0624: FormDefinition = {
  formCode: 'TDS',
  formName: 'Real Estate Transfer Disclosure Statement',
  variant: 'standard',
  version: 'v06-24',
  criticality: 'critical',

  systemPrompt: `You are an expert real estate transaction coordinator specializing in California Association of REALTORS® (C.A.R.) forms.
Your task is to extract all data from the provided images of a C.A.R. Form TDS (Real Estate Transfer Disclosure Statement, Revised 6/24).

${FORM_FOOTER_INSTRUCTION}

CRITICAL GUIDELINES:
1. Precision is paramount. Extract handwritten or typed text exactly as it appears.
2. CHECKBOXES: This form relies heavily on checkboxes. Visually inspect every box. If a box has an 'X', a checkmark, or is filled in, output true for that field. If it is empty, output false.
3. Note that in Section II-B and II-C, the form asks "Yes/No" questions. Pay careful attention to which specific box is checked.
4. Capture all handwritten explanations (e.g., descriptions of non-operating items, defect explanations, or agent notes) exactly as written. If an explanation line is blank, return null.
5. On Page 3, capture the buyer's signature and date in the 'Buyer's Signature' section. If the buyer signed, set 'buyer_signature' to true; otherwise false.

EXPECTED OUTPUT FORMAT:
You must return the extracted data strictly following this JSON template. Do not include markdown formatting or conversational text. Output ONLY valid JSON.

${JSON.stringify(TDS_TEMPLATE, null, 2)}`,

  userPrompt: 'Extract all fields from this Transfer Disclosure Statement and return valid JSON matching the template. Output ONLY valid JSON.',
};
